// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: currencies.proto

package currenciespb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
	server "github.com/unistack-org/micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CurrencyRatesService service

func NewCurrencyRatesServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CurrencyRatesService service

type CurrencyRatesService interface {
	GetRateCurrentCommon(ctx context.Context, req *GetRateCurrentCommonRequest, opts ...client.CallOption) (*RateData, error)
	GetRateByDateCommon(ctx context.Context, req *GetRateByDateCommonRequest, opts ...client.CallOption) (*RateData, error)
	GetRateCurrentForMerchant(ctx context.Context, req *GetRateCurrentForMerchantRequest, opts ...client.CallOption) (*RateData, error)
	GetRateByDateForMerchant(ctx context.Context, req *GetRateByDateForMerchantRequest, opts ...client.CallOption) (*RateData, error)
	ExchangeCurrencyCurrentCommon(ctx context.Context, req *ExchangeCurrencyCurrentCommonRequest, opts ...client.CallOption) (*ExchangeCurrencyResponse, error)
	ExchangeCurrencyCurrentForMerchant(ctx context.Context, req *ExchangeCurrencyCurrentForMerchantRequest, opts ...client.CallOption) (*ExchangeCurrencyResponse, error)
	ExchangeCurrencyByDateCommon(ctx context.Context, req *ExchangeCurrencyByDateCommonRequest, opts ...client.CallOption) (*ExchangeCurrencyResponse, error)
	ExchangeCurrencyByDateForMerchant(ctx context.Context, req *ExchangeCurrencyByDateForMerchantRequest, opts ...client.CallOption) (*ExchangeCurrencyResponse, error)
	GetCommonRateCorrectionRule(ctx context.Context, req *CommonCorrectionRuleRequest, opts ...client.CallOption) (*CorrectionRule, error)
	GetMerchantRateCorrectionRule(ctx context.Context, req *MerchantCorrectionRuleRequest, opts ...client.CallOption) (*CorrectionRule, error)
	AddCommonRateCorrectionRule(ctx context.Context, req *CommonCorrectionRule, opts ...client.CallOption) (*EmptyResponse, error)
	AddMerchantRateCorrectionRule(ctx context.Context, req *CorrectionRule, opts ...client.CallOption) (*EmptyResponse, error)
	GetSupportedCurrencies(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesList, error)
	GetSettlementCurrencies(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesList, error)
	GetPriceCurrencies(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesList, error)
	GetVatCurrencies(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesList, error)
	GetAccountingCurrencies(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesList, error)
	GetCurrenciesPrecision(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesPrecisionResponse, error)
}

type currencyRatesService struct {
	c    client.Client
	name string
}

func NewCurrencyRatesService(name string, c client.Client) CurrencyRatesService {
	return &currencyRatesService{
		c:    c,
		name: name,
	}
}

func (c *currencyRatesService) GetRateCurrentCommon(ctx context.Context, req *GetRateCurrentCommonRequest, opts ...client.CallOption) (*RateData, error) {
	rsp := &RateData{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetRateCurrentCommon", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) GetRateByDateCommon(ctx context.Context, req *GetRateByDateCommonRequest, opts ...client.CallOption) (*RateData, error) {
	rsp := &RateData{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetRateByDateCommon", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) GetRateCurrentForMerchant(ctx context.Context, req *GetRateCurrentForMerchantRequest, opts ...client.CallOption) (*RateData, error) {
	rsp := &RateData{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetRateCurrentForMerchant", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) GetRateByDateForMerchant(ctx context.Context, req *GetRateByDateForMerchantRequest, opts ...client.CallOption) (*RateData, error) {
	rsp := &RateData{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetRateByDateForMerchant", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) ExchangeCurrencyCurrentCommon(ctx context.Context, req *ExchangeCurrencyCurrentCommonRequest, opts ...client.CallOption) (*ExchangeCurrencyResponse, error) {
	rsp := &ExchangeCurrencyResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.ExchangeCurrencyCurrentCommon", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) ExchangeCurrencyCurrentForMerchant(ctx context.Context, req *ExchangeCurrencyCurrentForMerchantRequest, opts ...client.CallOption) (*ExchangeCurrencyResponse, error) {
	rsp := &ExchangeCurrencyResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.ExchangeCurrencyCurrentForMerchant", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) ExchangeCurrencyByDateCommon(ctx context.Context, req *ExchangeCurrencyByDateCommonRequest, opts ...client.CallOption) (*ExchangeCurrencyResponse, error) {
	rsp := &ExchangeCurrencyResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.ExchangeCurrencyByDateCommon", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) ExchangeCurrencyByDateForMerchant(ctx context.Context, req *ExchangeCurrencyByDateForMerchantRequest, opts ...client.CallOption) (*ExchangeCurrencyResponse, error) {
	rsp := &ExchangeCurrencyResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.ExchangeCurrencyByDateForMerchant", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) GetCommonRateCorrectionRule(ctx context.Context, req *CommonCorrectionRuleRequest, opts ...client.CallOption) (*CorrectionRule, error) {
	rsp := &CorrectionRule{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetCommonRateCorrectionRule", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) GetMerchantRateCorrectionRule(ctx context.Context, req *MerchantCorrectionRuleRequest, opts ...client.CallOption) (*CorrectionRule, error) {
	rsp := &CorrectionRule{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetMerchantRateCorrectionRule", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) AddCommonRateCorrectionRule(ctx context.Context, req *CommonCorrectionRule, opts ...client.CallOption) (*EmptyResponse, error) {
	rsp := &EmptyResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.AddCommonRateCorrectionRule", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) AddMerchantRateCorrectionRule(ctx context.Context, req *CorrectionRule, opts ...client.CallOption) (*EmptyResponse, error) {
	rsp := &EmptyResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.AddMerchantRateCorrectionRule", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) GetSupportedCurrencies(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesList, error) {
	rsp := &CurrenciesList{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetSupportedCurrencies", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) GetSettlementCurrencies(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesList, error) {
	rsp := &CurrenciesList{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetSettlementCurrencies", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) GetPriceCurrencies(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesList, error) {
	rsp := &CurrenciesList{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetPriceCurrencies", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) GetVatCurrencies(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesList, error) {
	rsp := &CurrenciesList{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetVatCurrencies", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) GetAccountingCurrencies(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesList, error) {
	rsp := &CurrenciesList{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetAccountingCurrencies", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *currencyRatesService) GetCurrenciesPrecision(ctx context.Context, req *EmptyRequest, opts ...client.CallOption) (*CurrenciesPrecisionResponse, error) {
	rsp := &CurrenciesPrecisionResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "CurrencyRatesService.GetCurrenciesPrecision", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// Server API for CurrencyRatesService service

type CurrencyRatesServiceHandler interface {
	GetRateCurrentCommon(context.Context, *GetRateCurrentCommonRequest, *RateData) error
	GetRateByDateCommon(context.Context, *GetRateByDateCommonRequest, *RateData) error
	GetRateCurrentForMerchant(context.Context, *GetRateCurrentForMerchantRequest, *RateData) error
	GetRateByDateForMerchant(context.Context, *GetRateByDateForMerchantRequest, *RateData) error
	ExchangeCurrencyCurrentCommon(context.Context, *ExchangeCurrencyCurrentCommonRequest, *ExchangeCurrencyResponse) error
	ExchangeCurrencyCurrentForMerchant(context.Context, *ExchangeCurrencyCurrentForMerchantRequest, *ExchangeCurrencyResponse) error
	ExchangeCurrencyByDateCommon(context.Context, *ExchangeCurrencyByDateCommonRequest, *ExchangeCurrencyResponse) error
	ExchangeCurrencyByDateForMerchant(context.Context, *ExchangeCurrencyByDateForMerchantRequest, *ExchangeCurrencyResponse) error
	GetCommonRateCorrectionRule(context.Context, *CommonCorrectionRuleRequest, *CorrectionRule) error
	GetMerchantRateCorrectionRule(context.Context, *MerchantCorrectionRuleRequest, *CorrectionRule) error
	AddCommonRateCorrectionRule(context.Context, *CommonCorrectionRule, *EmptyResponse) error
	AddMerchantRateCorrectionRule(context.Context, *CorrectionRule, *EmptyResponse) error
	GetSupportedCurrencies(context.Context, *EmptyRequest, *CurrenciesList) error
	GetSettlementCurrencies(context.Context, *EmptyRequest, *CurrenciesList) error
	GetPriceCurrencies(context.Context, *EmptyRequest, *CurrenciesList) error
	GetVatCurrencies(context.Context, *EmptyRequest, *CurrenciesList) error
	GetAccountingCurrencies(context.Context, *EmptyRequest, *CurrenciesList) error
	GetCurrenciesPrecision(context.Context, *EmptyRequest, *CurrenciesPrecisionResponse) error
}

func RegisterCurrencyRatesServiceHandler(s server.Server, hdlr CurrencyRatesServiceHandler, opts ...server.HandlerOption) error {
	type currencyRatesService interface {
		GetRateCurrentCommon(ctx context.Context, req *GetRateCurrentCommonRequest, rsp *RateData) error
		GetRateByDateCommon(ctx context.Context, req *GetRateByDateCommonRequest, rsp *RateData) error
		GetRateCurrentForMerchant(ctx context.Context, req *GetRateCurrentForMerchantRequest, rsp *RateData) error
		GetRateByDateForMerchant(ctx context.Context, req *GetRateByDateForMerchantRequest, rsp *RateData) error
		ExchangeCurrencyCurrentCommon(ctx context.Context, req *ExchangeCurrencyCurrentCommonRequest, rsp *ExchangeCurrencyResponse) error
		ExchangeCurrencyCurrentForMerchant(ctx context.Context, req *ExchangeCurrencyCurrentForMerchantRequest, rsp *ExchangeCurrencyResponse) error
		ExchangeCurrencyByDateCommon(ctx context.Context, req *ExchangeCurrencyByDateCommonRequest, rsp *ExchangeCurrencyResponse) error
		ExchangeCurrencyByDateForMerchant(ctx context.Context, req *ExchangeCurrencyByDateForMerchantRequest, rsp *ExchangeCurrencyResponse) error
		GetCommonRateCorrectionRule(ctx context.Context, req *CommonCorrectionRuleRequest, rsp *CorrectionRule) error
		GetMerchantRateCorrectionRule(ctx context.Context, req *MerchantCorrectionRuleRequest, rsp *CorrectionRule) error
		AddCommonRateCorrectionRule(ctx context.Context, req *CommonCorrectionRule, rsp *EmptyResponse) error
		AddMerchantRateCorrectionRule(ctx context.Context, req *CorrectionRule, rsp *EmptyResponse) error
		GetSupportedCurrencies(ctx context.Context, req *EmptyRequest, rsp *CurrenciesList) error
		GetSettlementCurrencies(ctx context.Context, req *EmptyRequest, rsp *CurrenciesList) error
		GetPriceCurrencies(ctx context.Context, req *EmptyRequest, rsp *CurrenciesList) error
		GetVatCurrencies(ctx context.Context, req *EmptyRequest, rsp *CurrenciesList) error
		GetAccountingCurrencies(ctx context.Context, req *EmptyRequest, rsp *CurrenciesList) error
		GetCurrenciesPrecision(ctx context.Context, req *EmptyRequest, rsp *CurrenciesPrecisionResponse) error
	}
	type CurrencyRatesService struct {
		currencyRatesService
	}
	h := &currencyRatesServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CurrencyRatesService{h}, opts...))
}

type currencyRatesServiceHandler struct {
	CurrencyRatesServiceHandler
}

func (h *currencyRatesServiceHandler) GetRateCurrentCommon(ctx context.Context, req *GetRateCurrentCommonRequest, rsp *RateData) error {
	return h.CurrencyRatesServiceHandler.GetRateCurrentCommon(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) GetRateByDateCommon(ctx context.Context, req *GetRateByDateCommonRequest, rsp *RateData) error {
	return h.CurrencyRatesServiceHandler.GetRateByDateCommon(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) GetRateCurrentForMerchant(ctx context.Context, req *GetRateCurrentForMerchantRequest, rsp *RateData) error {
	return h.CurrencyRatesServiceHandler.GetRateCurrentForMerchant(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) GetRateByDateForMerchant(ctx context.Context, req *GetRateByDateForMerchantRequest, rsp *RateData) error {
	return h.CurrencyRatesServiceHandler.GetRateByDateForMerchant(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) ExchangeCurrencyCurrentCommon(ctx context.Context, req *ExchangeCurrencyCurrentCommonRequest, rsp *ExchangeCurrencyResponse) error {
	return h.CurrencyRatesServiceHandler.ExchangeCurrencyCurrentCommon(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) ExchangeCurrencyCurrentForMerchant(ctx context.Context, req *ExchangeCurrencyCurrentForMerchantRequest, rsp *ExchangeCurrencyResponse) error {
	return h.CurrencyRatesServiceHandler.ExchangeCurrencyCurrentForMerchant(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) ExchangeCurrencyByDateCommon(ctx context.Context, req *ExchangeCurrencyByDateCommonRequest, rsp *ExchangeCurrencyResponse) error {
	return h.CurrencyRatesServiceHandler.ExchangeCurrencyByDateCommon(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) ExchangeCurrencyByDateForMerchant(ctx context.Context, req *ExchangeCurrencyByDateForMerchantRequest, rsp *ExchangeCurrencyResponse) error {
	return h.CurrencyRatesServiceHandler.ExchangeCurrencyByDateForMerchant(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) GetCommonRateCorrectionRule(ctx context.Context, req *CommonCorrectionRuleRequest, rsp *CorrectionRule) error {
	return h.CurrencyRatesServiceHandler.GetCommonRateCorrectionRule(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) GetMerchantRateCorrectionRule(ctx context.Context, req *MerchantCorrectionRuleRequest, rsp *CorrectionRule) error {
	return h.CurrencyRatesServiceHandler.GetMerchantRateCorrectionRule(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) AddCommonRateCorrectionRule(ctx context.Context, req *CommonCorrectionRule, rsp *EmptyResponse) error {
	return h.CurrencyRatesServiceHandler.AddCommonRateCorrectionRule(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) AddMerchantRateCorrectionRule(ctx context.Context, req *CorrectionRule, rsp *EmptyResponse) error {
	return h.CurrencyRatesServiceHandler.AddMerchantRateCorrectionRule(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) GetSupportedCurrencies(ctx context.Context, req *EmptyRequest, rsp *CurrenciesList) error {
	return h.CurrencyRatesServiceHandler.GetSupportedCurrencies(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) GetSettlementCurrencies(ctx context.Context, req *EmptyRequest, rsp *CurrenciesList) error {
	return h.CurrencyRatesServiceHandler.GetSettlementCurrencies(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) GetPriceCurrencies(ctx context.Context, req *EmptyRequest, rsp *CurrenciesList) error {
	return h.CurrencyRatesServiceHandler.GetPriceCurrencies(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) GetVatCurrencies(ctx context.Context, req *EmptyRequest, rsp *CurrenciesList) error {
	return h.CurrencyRatesServiceHandler.GetVatCurrencies(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) GetAccountingCurrencies(ctx context.Context, req *EmptyRequest, rsp *CurrenciesList) error {
	return h.CurrencyRatesServiceHandler.GetAccountingCurrencies(ctx, req, rsp)
}

func (h *currencyRatesServiceHandler) GetCurrenciesPrecision(ctx context.Context, req *EmptyRequest, rsp *CurrenciesPrecisionResponse) error {
	return h.CurrencyRatesServiceHandler.GetCurrenciesPrecision(ctx, req, rsp)
}
