// Code generated by mockery v2.2.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/micro/go-micro/client"

	mock "github.com/stretchr/testify/mock"

	recurringpb "github.com/paysuper/paysuper-proto/go/recurringpb"
)

// RepositoryService is an autogenerated mock type for the RepositoryService type
type RepositoryService struct {
	mock.Mock
}

// DeleteSavedCard provides a mock function with given fields: ctx, in, opts
func (_m *RepositoryService) DeleteSavedCard(ctx context.Context, in *recurringpb.DeleteSavedCardRequest, opts ...client.CallOption) (*recurringpb.DeleteSavedCardResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *recurringpb.DeleteSavedCardResponse
	if rf, ok := ret.Get(0).(func(context.Context, *recurringpb.DeleteSavedCardRequest, ...client.CallOption) *recurringpb.DeleteSavedCardResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recurringpb.DeleteSavedCardResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *recurringpb.DeleteSavedCardRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSavedCardById provides a mock function with given fields: ctx, in, opts
func (_m *RepositoryService) FindSavedCardById(ctx context.Context, in *recurringpb.FindByStringValue, opts ...client.CallOption) (*recurringpb.SavedCard, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *recurringpb.SavedCard
	if rf, ok := ret.Get(0).(func(context.Context, *recurringpb.FindByStringValue, ...client.CallOption) *recurringpb.SavedCard); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recurringpb.SavedCard)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *recurringpb.FindByStringValue, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSavedCards provides a mock function with given fields: ctx, in, opts
func (_m *RepositoryService) FindSavedCards(ctx context.Context, in *recurringpb.SavedCardRequest, opts ...client.CallOption) (*recurringpb.SavedCardList, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *recurringpb.SavedCardList
	if rf, ok := ret.Get(0).(func(context.Context, *recurringpb.SavedCardRequest, ...client.CallOption) *recurringpb.SavedCardList); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recurringpb.SavedCardList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *recurringpb.SavedCardRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertSavedCard provides a mock function with given fields: ctx, in, opts
func (_m *RepositoryService) InsertSavedCard(ctx context.Context, in *recurringpb.SavedCardRequest, opts ...client.CallOption) (*recurringpb.Result, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *recurringpb.Result
	if rf, ok := ret.Get(0).(func(context.Context, *recurringpb.SavedCardRequest, ...client.CallOption) *recurringpb.Result); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recurringpb.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *recurringpb.SavedCardRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
