// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notifier.proto

package notifierpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckUserRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	SecretKey            string   `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	IsLiveProject        bool     `protobuf:"varint,4,opt,name=is_live_project,json=isLiveProject,proto3" json:"is_live_project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *CheckUserRequest) Reset()         { *m = CheckUserRequest{} }
func (m *CheckUserRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUserRequest) ProtoMessage()    {}
func (*CheckUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c0fc606bc4470de, []int{0}
}

func (m *CheckUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserRequest.Unmarshal(m, b)
}
func (m *CheckUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserRequest.Marshal(b, m, deterministic)
}
func (m *CheckUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserRequest.Merge(m, src)
}
func (m *CheckUserRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUserRequest.Size(m)
}
func (m *CheckUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserRequest proto.InternalMessageInfo

func (m *CheckUserRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CheckUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CheckUserRequest) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *CheckUserRequest) GetIsLiveProject() bool {
	if m != nil {
		return m.IsLiveProject
	}
	return false
}

type CheckUserResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *CheckUserResponse) Reset()         { *m = CheckUserResponse{} }
func (m *CheckUserResponse) String() string { return proto.CompactTextString(m) }
func (*CheckUserResponse) ProtoMessage()    {}
func (*CheckUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c0fc606bc4470de, []int{1}
}

func (m *CheckUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserResponse.Unmarshal(m, b)
}
func (m *CheckUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserResponse.Marshal(b, m, deterministic)
}
func (m *CheckUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserResponse.Merge(m, src)
}
func (m *CheckUserResponse) XXX_Size() int {
	return xxx_messageInfo_CheckUserResponse.Size(m)
}
func (m *CheckUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserResponse proto.InternalMessageInfo

func (m *CheckUserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CheckUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type User struct {
	// @inject_tag: json:"id"
	//
	// The unique identifier for the customer in the paysuper.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"object"
	//
	// The system constant that contains the returned object's type.
	Object string `protobuf:"bytes,2,opt,name=object,proto3" json:"object"`
	// @inject_tag: json:"external_id"
	//
	// The unique identifier for the customer in the merchant project.
	ExternalId string `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id"`
	// @inject_tag: json:"name"
	//
	// The customer's name.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	// @inject_tag: json:"email"
	//
	// The customer's email address.
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email"`
	// @inject_tag: json:"email_verified"
	//
	// Whether the customer's email address has been verified on the merchant side.
	EmailVerified bool `protobuf:"varint,6,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified"`
	// @inject_tag: json:"phone"
	//
	// The customer's phone number.
	Phone string `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone"`
	// @inject_tag: json:"phone_verified"
	//
	// Whether the customer's phone number has been verified on the merchant side.
	PhoneVerified bool `protobuf:"varint,8,opt,name=phone_verified,json=phoneVerified,proto3" json:"phone_verified"`
	// @inject_tag: json:"ip"
	//
	// The customer's IP address.
	Ip string `protobuf:"bytes,9,opt,name=ip,proto3" json:"ip"`
	// @inject_tag: json:"locale"
	//
	// The customer's locale name. The language code in ISO 639-1 (for instance en-US).
	Locale string `protobuf:"bytes,10,opt,name=locale,proto3" json:"locale"`
	// @inject_tag: json:"address"
	//
	// The customer's address details.
	Address *BillingAddress `protobuf:"bytes,11,opt,name=address,proto3" json:"address"`
	// @inject_tag: json:"metadata"
	//
	// A string-value description that you can attach to the customer's object. It can be useful for storing additional information about your customer's payment.
	Metadata map[string]string `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// @inject_tag: json:"notify_new_region"
	//
	// Has the value true if the customer confirmed to receive the PaySuper newsletter about the beginning of payment acceptance in new regions.
	NotifyNewRegion bool `protobuf:"varint,13,opt,name=notify_new_region,json=notifyNewRegion,proto3" json:"notify_new_region"`
	// @inject_tag: json:"notify_new_region_email"
	//
	// The customer’s email for a newsletter about the beginning of payment acceptance in new regions.
	NotifyNewRegionEmail string   `protobuf:"bytes,14,opt,name=notify_new_region_email,json=notifyNewRegionEmail,proto3" json:"notify_new_region_email"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c0fc606bc4470de, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *User) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetPhoneVerified() bool {
	if m != nil {
		return m.PhoneVerified
	}
	return false
}

func (m *User) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *User) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *User) GetAddress() *BillingAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *User) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *User) GetNotifyNewRegion() bool {
	if m != nil {
		return m.NotifyNewRegion
	}
	return false
}

func (m *User) GetNotifyNewRegionEmail() string {
	if m != nil {
		return m.NotifyNewRegionEmail
	}
	return ""
}

type BillingAddress struct {
	// @inject_tag: json:"country"
	//
	// The customer's country. Two-letter country code in ISO 3166-1, in uppercase (for instance US).
	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country"`
	// @inject_tag: json:"city"
	//
	// The customer’s city.
	City string `protobuf:"bytes,2,opt,name=city,proto3" json:"city"`
	// @inject_tag: json:"postal_code"
	//
	// The customer's postal code.
	PostalCode string `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code"`
	// @inject_tag: json:"state"
	//
	// The customer's state code in ISO 3166-2.
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *BillingAddress) Reset()         { *m = BillingAddress{} }
func (m *BillingAddress) String() string { return proto.CompactTextString(m) }
func (*BillingAddress) ProtoMessage()    {}
func (*BillingAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c0fc606bc4470de, []int{3}
}

func (m *BillingAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BillingAddress.Unmarshal(m, b)
}
func (m *BillingAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BillingAddress.Marshal(b, m, deterministic)
}
func (m *BillingAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BillingAddress.Merge(m, src)
}
func (m *BillingAddress) XXX_Size() int {
	return xxx_messageInfo_BillingAddress.Size(m)
}
func (m *BillingAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_BillingAddress.DiscardUnknown(m)
}

var xxx_messageInfo_BillingAddress proto.InternalMessageInfo

func (m *BillingAddress) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *BillingAddress) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *BillingAddress) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *BillingAddress) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckUserRequest)(nil), "notifier.CheckUserRequest")
	proto.RegisterType((*CheckUserResponse)(nil), "notifier.CheckUserResponse")
	proto.RegisterType((*User)(nil), "notifier.User")
	proto.RegisterMapType((map[string]string)(nil), "notifier.User.MetadataEntry")
	proto.RegisterType((*BillingAddress)(nil), "notifier.BillingAddress")
}

func init() {
	proto.RegisterFile("notifier.proto", fileDescriptor_1c0fc606bc4470de)
}

var fileDescriptor_1c0fc606bc4470de = []byte{
	// 547 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0xdd, 0x7e, 0x65, 0xba, 0x4d, 0x77, 0xad, 0x15, 0x58, 0x05, 0x44, 0x15, 0x09, 0x54,
	0x71, 0xe8, 0xa1, 0x08, 0x69, 0x05, 0x27, 0x76, 0x55, 0x24, 0x04, 0xac, 0x50, 0x10, 0x48, 0x70,
	0x89, 0xdc, 0x64, 0xe8, 0x9a, 0xa6, 0x71, 0xb0, 0x9d, 0x2e, 0xf9, 0x15, 0x1c, 0xf8, 0xc3, 0xc8,
	0x76, 0xd2, 0xd2, 0x85, 0xdb, 0xbc, 0x37, 0x7e, 0xe3, 0x99, 0xf1, 0x33, 0x04, 0xb9, 0xd0, 0xfc,
	0x1b, 0x47, 0x39, 0x2b, 0xa4, 0xd0, 0x82, 0xf4, 0x1b, 0x1c, 0xfe, 0xf2, 0xe0, 0xe4, 0xf2, 0x1a,
	0x93, 0xf5, 0x27, 0x85, 0x32, 0xc2, 0x1f, 0x25, 0x2a, 0x4d, 0x4e, 0xe0, 0xa8, 0x94, 0x19, 0xf5,
	0x26, 0xde, 0xd4, 0x8f, 0x4c, 0x48, 0x42, 0x68, 0x97, 0x0a, 0x25, 0x6d, 0x4d, 0xbc, 0xe9, 0x60,
	0x1e, 0xcc, 0x76, 0xf5, 0xac, 0xcc, 0xe6, 0xc8, 0x43, 0x00, 0x85, 0x89, 0x44, 0x1d, 0xaf, 0xb1,
	0xa2, 0x47, 0x56, 0xec, 0x3b, 0xe6, 0x2d, 0x56, 0xe4, 0x09, 0x8c, 0xb8, 0x8a, 0x33, 0xbe, 0xc5,
	0xb8, 0x90, 0xe2, 0x3b, 0x26, 0x9a, 0xb6, 0x27, 0xde, 0xb4, 0x1f, 0x0d, 0xb9, 0x7a, 0xc7, 0xb7,
	0xf8, 0xc1, 0x91, 0xe1, 0x02, 0x4e, 0xff, 0x6a, 0x48, 0x15, 0x22, 0x57, 0x48, 0xee, 0x42, 0x57,
	0x69, 0xa6, 0x4b, 0x65, 0x9b, 0xea, 0x44, 0x35, 0x22, 0x14, 0x7a, 0x1b, 0x54, 0x8a, 0xad, 0xd0,
	0xb6, 0xe6, 0x47, 0x0d, 0x0c, 0x7f, 0xb7, 0xa1, 0x6d, 0x4a, 0x90, 0x00, 0x5a, 0x3c, 0xad, 0x67,
	0x69, 0xf1, 0xd4, 0x94, 0x12, 0x4b, 0x7b, 0xbd, 0x53, 0xd4, 0x88, 0x3c, 0x82, 0x01, 0xfe, 0xd4,
	0x28, 0x73, 0x96, 0xc5, 0x3c, 0xad, 0xfb, 0x87, 0x86, 0x7a, 0x93, 0x12, 0x02, 0xed, 0x9c, 0x6d,
	0xd0, 0x76, 0xed, 0x47, 0x36, 0x26, 0x67, 0xd0, 0xc1, 0x0d, 0xe3, 0x19, 0xed, 0x58, 0xd2, 0x01,
	0xf2, 0x18, 0x02, 0x1b, 0xc4, 0x5b, 0x94, 0x66, 0x4d, 0x29, 0xed, 0xba, 0x49, 0x2d, 0xfb, 0xb9,
	0x26, 0x8d, 0xb8, 0xb8, 0x16, 0x39, 0xd2, 0x9e, 0x13, 0x5b, 0x60, 0xc4, 0x36, 0xd8, 0x8b, 0xfb,
	0x4e, 0x6c, 0xd9, 0x9d, 0xd8, 0x8c, 0x55, 0x50, 0xbf, 0x1e, 0xab, 0x30, 0x63, 0x65, 0x22, 0x61,
	0x19, 0x52, 0x70, 0x63, 0x39, 0x44, 0xe6, 0xd0, 0x63, 0x69, 0x2a, 0x51, 0x29, 0x3a, 0xb0, 0x8f,
	0x47, 0xf7, 0x8f, 0x77, 0xc1, 0xb3, 0x8c, 0xe7, 0xab, 0x57, 0x2e, 0x1f, 0x35, 0x07, 0xc9, 0x39,
	0xf4, 0x37, 0xa8, 0x59, 0xca, 0x34, 0xa3, 0xc7, 0x93, 0xa3, 0xe9, 0x60, 0xfe, 0xe0, 0xf0, 0xc5,
	0x67, 0xef, 0xeb, 0xf4, 0x22, 0xd7, 0xb2, 0x8a, 0x76, 0xa7, 0xc9, 0x53, 0x38, 0xb5, 0x07, 0xab,
	0x38, 0xc7, 0x9b, 0x58, 0xe2, 0x8a, 0x8b, 0x9c, 0x0e, 0x6d, 0xff, 0x23, 0x97, 0xb8, 0xc2, 0x9b,
	0xc8, 0xd2, 0xe4, 0x39, 0xdc, 0xfb, 0xe7, 0x6c, 0xec, 0xb6, 0x19, 0xd8, 0x11, 0xce, 0x6e, 0x29,
	0x16, 0x26, 0x37, 0x7e, 0x09, 0xc3, 0x83, 0xdb, 0x8d, 0x5b, 0x8d, 0xe1, 0x6a, 0xb7, 0xae, 0xb1,
	0x32, 0x8b, 0xdd, 0xb2, 0xac, 0x6c, 0x3c, 0xe1, 0xc0, 0x8b, 0xd6, 0xb9, 0x17, 0x96, 0x10, 0x1c,
	0x0e, 0x6d, 0x1c, 0x94, 0x88, 0xd2, 0x14, 0xaa, 0x2b, 0x34, 0xd0, 0xbc, 0x77, 0xc2, 0x75, 0x55,
	0x17, 0xb1, 0xb1, 0x31, 0x49, 0x21, 0x94, 0x66, 0x59, 0x9c, 0x88, 0x14, 0x1b, 0x93, 0x38, 0xea,
	0x52, 0xa4, 0xd6, 0x10, 0xc6, 0x9a, 0x8d, 0x4b, 0x1c, 0x98, 0x7f, 0x81, 0xd1, 0x55, 0xbd, 0xbf,
	0x8f, 0x28, 0xb7, 0x3c, 0x41, 0xf2, 0x1a, 0xfc, 0x9d, 0xcd, 0xc9, 0x78, 0xbf, 0xde, 0xdb, 0x9f,
	0x71, 0x7c, 0xff, 0xbf, 0x39, 0xf7, 0x2f, 0xc2, 0x3b, 0x17, 0xc7, 0x5f, 0xa1, 0xc9, 0x17, 0xcb,
	0x65, 0xd7, 0xfe, 0xef, 0x67, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xc8, 0xc4, 0x2b, 0xf1,
	0x03, 0x00, 0x00,
}
