// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cardpay.proto

package billingpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CardPayAddress struct {
	Country              string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Street               string   `protobuf:"bytes,5,opt,name=street,proto3" json:"street,omitempty"`
	Zip                  string   `protobuf:"bytes,6,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardPayAddress) Reset()         { *m = CardPayAddress{} }
func (m *CardPayAddress) String() string { return proto.CompactTextString(m) }
func (*CardPayAddress) ProtoMessage()    {}
func (*CardPayAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{0}
}

func (m *CardPayAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayAddress.Unmarshal(m, b)
}
func (m *CardPayAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayAddress.Marshal(b, m, deterministic)
}
func (m *CardPayAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayAddress.Merge(m, src)
}
func (m *CardPayAddress) XXX_Size() int {
	return xxx_messageInfo_CardPayAddress.Size(m)
}
func (m *CardPayAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayAddress.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayAddress proto.InternalMessageInfo

func (m *CardPayAddress) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CardPayAddress) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CardPayAddress) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CardPayAddress) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CardPayAddress) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CardPayAddress) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type CardPayItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardPayItem) Reset()         { *m = CardPayItem{} }
func (m *CardPayItem) String() string { return proto.CompactTextString(m) }
func (*CardPayItem) ProtoMessage()    {}
func (*CardPayItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{1}
}

func (m *CardPayItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayItem.Unmarshal(m, b)
}
func (m *CardPayItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayItem.Marshal(b, m, deterministic)
}
func (m *CardPayItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayItem.Merge(m, src)
}
func (m *CardPayItem) XXX_Size() int {
	return xxx_messageInfo_CardPayItem.Size(m)
}
func (m *CardPayItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayItem.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayItem proto.InternalMessageInfo

func (m *CardPayItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CardPayItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CardPayItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CardPayItem) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CardPayMerchantOrder struct {
	//// @inject_tag: validate:"required,hexadecimal,len=24"
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string          `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Items                []*CardPayItem  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	ShippingAddress      *CardPayAddress `protobuf:"bytes,4,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CardPayMerchantOrder) Reset()         { *m = CardPayMerchantOrder{} }
func (m *CardPayMerchantOrder) String() string { return proto.CompactTextString(m) }
func (*CardPayMerchantOrder) ProtoMessage()    {}
func (*CardPayMerchantOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{2}
}

func (m *CardPayMerchantOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayMerchantOrder.Unmarshal(m, b)
}
func (m *CardPayMerchantOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayMerchantOrder.Marshal(b, m, deterministic)
}
func (m *CardPayMerchantOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayMerchantOrder.Merge(m, src)
}
func (m *CardPayMerchantOrder) XXX_Size() int {
	return xxx_messageInfo_CardPayMerchantOrder.Size(m)
}
func (m *CardPayMerchantOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayMerchantOrder.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayMerchantOrder proto.InternalMessageInfo

func (m *CardPayMerchantOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CardPayMerchantOrder) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CardPayMerchantOrder) GetItems() []*CardPayItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *CardPayMerchantOrder) GetShippingAddress() *CardPayAddress {
	if m != nil {
		return m.ShippingAddress
	}
	return nil
}

type CallbackCardPayBankCardAccount struct {
	Holder               string   `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	IssuingCountryCode   string   `protobuf:"bytes,2,opt,name=issuing_country_code,json=issuingCountryCode,proto3" json:"issuing_country_code,omitempty"`
	MaskedPan            string   `protobuf:"bytes,3,opt,name=masked_pan,json=maskedPan,proto3" json:"masked_pan,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackCardPayBankCardAccount) Reset()         { *m = CallbackCardPayBankCardAccount{} }
func (m *CallbackCardPayBankCardAccount) String() string { return proto.CompactTextString(m) }
func (*CallbackCardPayBankCardAccount) ProtoMessage()    {}
func (*CallbackCardPayBankCardAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{3}
}

func (m *CallbackCardPayBankCardAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackCardPayBankCardAccount.Unmarshal(m, b)
}
func (m *CallbackCardPayBankCardAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackCardPayBankCardAccount.Marshal(b, m, deterministic)
}
func (m *CallbackCardPayBankCardAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackCardPayBankCardAccount.Merge(m, src)
}
func (m *CallbackCardPayBankCardAccount) XXX_Size() int {
	return xxx_messageInfo_CallbackCardPayBankCardAccount.Size(m)
}
func (m *CallbackCardPayBankCardAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackCardPayBankCardAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackCardPayBankCardAccount proto.InternalMessageInfo

func (m *CallbackCardPayBankCardAccount) GetHolder() string {
	if m != nil {
		return m.Holder
	}
	return ""
}

func (m *CallbackCardPayBankCardAccount) GetIssuingCountryCode() string {
	if m != nil {
		return m.IssuingCountryCode
	}
	return ""
}

func (m *CallbackCardPayBankCardAccount) GetMaskedPan() string {
	if m != nil {
		return m.MaskedPan
	}
	return ""
}

func (m *CallbackCardPayBankCardAccount) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CallbackCardPayCryptoCurrencyAccount struct {
	CryptoAddress        string   `protobuf:"bytes,1,opt,name=crypto_address,json=cryptoAddress,proto3" json:"crypto_address,omitempty"`
	CryptoTransactionId  string   `protobuf:"bytes,2,opt,name=crypto_transaction_id,json=cryptoTransactionId,proto3" json:"crypto_transaction_id,omitempty"`
	PrcAmount            string   `protobuf:"bytes,3,opt,name=prc_amount,json=prcAmount,proto3" json:"prc_amount,omitempty"`
	PrcCurrency          string   `protobuf:"bytes,4,opt,name=prc_currency,json=prcCurrency,proto3" json:"prc_currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackCardPayCryptoCurrencyAccount) Reset()         { *m = CallbackCardPayCryptoCurrencyAccount{} }
func (m *CallbackCardPayCryptoCurrencyAccount) String() string { return proto.CompactTextString(m) }
func (*CallbackCardPayCryptoCurrencyAccount) ProtoMessage()    {}
func (*CallbackCardPayCryptoCurrencyAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{4}
}

func (m *CallbackCardPayCryptoCurrencyAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount.Unmarshal(m, b)
}
func (m *CallbackCardPayCryptoCurrencyAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount.Marshal(b, m, deterministic)
}
func (m *CallbackCardPayCryptoCurrencyAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount.Merge(m, src)
}
func (m *CallbackCardPayCryptoCurrencyAccount) XXX_Size() int {
	return xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount.Size(m)
}
func (m *CallbackCardPayCryptoCurrencyAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount proto.InternalMessageInfo

func (m *CallbackCardPayCryptoCurrencyAccount) GetCryptoAddress() string {
	if m != nil {
		return m.CryptoAddress
	}
	return ""
}

func (m *CallbackCardPayCryptoCurrencyAccount) GetCryptoTransactionId() string {
	if m != nil {
		return m.CryptoTransactionId
	}
	return ""
}

func (m *CallbackCardPayCryptoCurrencyAccount) GetPrcAmount() string {
	if m != nil {
		return m.PrcAmount
	}
	return ""
}

func (m *CallbackCardPayCryptoCurrencyAccount) GetPrcCurrency() string {
	if m != nil {
		return m.PrcCurrency
	}
	return ""
}

type CardPayCustomer struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Locale               string   `protobuf:"bytes,4,opt,name=locale,proto3" json:"locale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardPayCustomer) Reset()         { *m = CardPayCustomer{} }
func (m *CardPayCustomer) String() string { return proto.CompactTextString(m) }
func (*CardPayCustomer) ProtoMessage()    {}
func (*CardPayCustomer) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{5}
}

func (m *CardPayCustomer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayCustomer.Unmarshal(m, b)
}
func (m *CardPayCustomer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayCustomer.Marshal(b, m, deterministic)
}
func (m *CardPayCustomer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayCustomer.Merge(m, src)
}
func (m *CardPayCustomer) XXX_Size() int {
	return xxx_messageInfo_CardPayCustomer.Size(m)
}
func (m *CardPayCustomer) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayCustomer.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayCustomer proto.InternalMessageInfo

func (m *CardPayCustomer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CardPayCustomer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CardPayCustomer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CardPayCustomer) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

type CardPayEWalletAccount struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardPayEWalletAccount) Reset()         { *m = CardPayEWalletAccount{} }
func (m *CardPayEWalletAccount) String() string { return proto.CompactTextString(m) }
func (*CardPayEWalletAccount) ProtoMessage()    {}
func (*CardPayEWalletAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{6}
}

func (m *CardPayEWalletAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayEWalletAccount.Unmarshal(m, b)
}
func (m *CardPayEWalletAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayEWalletAccount.Marshal(b, m, deterministic)
}
func (m *CardPayEWalletAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayEWalletAccount.Merge(m, src)
}
func (m *CardPayEWalletAccount) XXX_Size() int {
	return xxx_messageInfo_CardPayEWalletAccount.Size(m)
}
func (m *CardPayEWalletAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayEWalletAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayEWalletAccount proto.InternalMessageInfo

func (m *CardPayEWalletAccount) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CallbackCardPayPaymentData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	AuthCode             string   `protobuf:"bytes,3,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	Created              string   `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Currency             string   `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	DeclineCode          string   `protobuf:"bytes,6,opt,name=decline_code,json=declineCode,proto3" json:"decline_code,omitempty"`
	DeclineReason        string   `protobuf:"bytes,7,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Is_3D                bool     `protobuf:"varint,9,opt,name=is_3d,json=is3d,proto3" json:"is_3d,omitempty"`
	Note                 string   `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
	Rrn                  string   `protobuf:"bytes,11,opt,name=rrn,proto3" json:"rrn,omitempty"`
	Status               string   `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackCardPayPaymentData) Reset()         { *m = CallbackCardPayPaymentData{} }
func (m *CallbackCardPayPaymentData) String() string { return proto.CompactTextString(m) }
func (*CallbackCardPayPaymentData) ProtoMessage()    {}
func (*CallbackCardPayPaymentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{7}
}

func (m *CallbackCardPayPaymentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackCardPayPaymentData.Unmarshal(m, b)
}
func (m *CallbackCardPayPaymentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackCardPayPaymentData.Marshal(b, m, deterministic)
}
func (m *CallbackCardPayPaymentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackCardPayPaymentData.Merge(m, src)
}
func (m *CallbackCardPayPaymentData) XXX_Size() int {
	return xxx_messageInfo_CallbackCardPayPaymentData.Size(m)
}
func (m *CallbackCardPayPaymentData) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackCardPayPaymentData.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackCardPayPaymentData proto.InternalMessageInfo

func (m *CallbackCardPayPaymentData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CallbackCardPayPaymentData) GetAuthCode() string {
	if m != nil {
		return m.AuthCode
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetDeclineCode() string {
	if m != nil {
		return m.DeclineCode
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetDeclineReason() string {
	if m != nil {
		return m.DeclineReason
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetIs_3D() bool {
	if m != nil {
		return m.Is_3D
	}
	return false
}

func (m *CallbackCardPayPaymentData) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetRrn() string {
	if m != nil {
		return m.Rrn
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CardPayCallbackRecurringDataFilling struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardPayCallbackRecurringDataFilling) Reset()         { *m = CardPayCallbackRecurringDataFilling{} }
func (m *CardPayCallbackRecurringDataFilling) String() string { return proto.CompactTextString(m) }
func (*CardPayCallbackRecurringDataFilling) ProtoMessage()    {}
func (*CardPayCallbackRecurringDataFilling) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{8}
}

func (m *CardPayCallbackRecurringDataFilling) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayCallbackRecurringDataFilling.Unmarshal(m, b)
}
func (m *CardPayCallbackRecurringDataFilling) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayCallbackRecurringDataFilling.Marshal(b, m, deterministic)
}
func (m *CardPayCallbackRecurringDataFilling) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayCallbackRecurringDataFilling.Merge(m, src)
}
func (m *CardPayCallbackRecurringDataFilling) XXX_Size() int {
	return xxx_messageInfo_CardPayCallbackRecurringDataFilling.Size(m)
}
func (m *CardPayCallbackRecurringDataFilling) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayCallbackRecurringDataFilling.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayCallbackRecurringDataFilling proto.InternalMessageInfo

func (m *CardPayCallbackRecurringDataFilling) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CardPayCallbackRecurringData struct {
	Id                   string                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               float64                              `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	AuthCode             string                               `protobuf:"bytes,3,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	Created              string                               `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Currency             string                               `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	DeclineCode          string                               `protobuf:"bytes,6,opt,name=decline_code,json=declineCode,proto3" json:"decline_code,omitempty"`
	DeclineReason        string                               `protobuf:"bytes,7,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"`
	Description          string                               `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Is_3D                bool                                 `protobuf:"varint,9,opt,name=is_3d,json=is3d,proto3" json:"is_3d,omitempty"`
	Note                 string                               `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
	Rrn                  string                               `protobuf:"bytes,11,opt,name=rrn,proto3" json:"rrn,omitempty"`
	Status               string                               `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	Filing               *CardPayCallbackRecurringDataFilling `protobuf:"bytes,13,opt,name=filing,proto3" json:"filing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *CardPayCallbackRecurringData) Reset()         { *m = CardPayCallbackRecurringData{} }
func (m *CardPayCallbackRecurringData) String() string { return proto.CompactTextString(m) }
func (*CardPayCallbackRecurringData) ProtoMessage()    {}
func (*CardPayCallbackRecurringData) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{9}
}

func (m *CardPayCallbackRecurringData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayCallbackRecurringData.Unmarshal(m, b)
}
func (m *CardPayCallbackRecurringData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayCallbackRecurringData.Marshal(b, m, deterministic)
}
func (m *CardPayCallbackRecurringData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayCallbackRecurringData.Merge(m, src)
}
func (m *CardPayCallbackRecurringData) XXX_Size() int {
	return xxx_messageInfo_CardPayCallbackRecurringData.Size(m)
}
func (m *CardPayCallbackRecurringData) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayCallbackRecurringData.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayCallbackRecurringData proto.InternalMessageInfo

func (m *CardPayCallbackRecurringData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CardPayCallbackRecurringData) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CardPayCallbackRecurringData) GetAuthCode() string {
	if m != nil {
		return m.AuthCode
	}
	return ""
}

func (m *CardPayCallbackRecurringData) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *CardPayCallbackRecurringData) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *CardPayCallbackRecurringData) GetDeclineCode() string {
	if m != nil {
		return m.DeclineCode
	}
	return ""
}

func (m *CardPayCallbackRecurringData) GetDeclineReason() string {
	if m != nil {
		return m.DeclineReason
	}
	return ""
}

func (m *CardPayCallbackRecurringData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CardPayCallbackRecurringData) GetIs_3D() bool {
	if m != nil {
		return m.Is_3D
	}
	return false
}

func (m *CardPayCallbackRecurringData) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *CardPayCallbackRecurringData) GetRrn() string {
	if m != nil {
		return m.Rrn
	}
	return ""
}

func (m *CardPayCallbackRecurringData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CardPayCallbackRecurringData) GetFiling() *CardPayCallbackRecurringDataFilling {
	if m != nil {
		return m.Filing
	}
	return nil
}

type CardPayPaymentCallback struct {
	MerchantOrder         *CardPayMerchantOrder                 `protobuf:"bytes,1,opt,name=merchant_order,json=merchantOrder,proto3" json:"merchant_order,omitempty"`
	PaymentMethod         string                                `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	CallbackTime          string                                `protobuf:"bytes,3,opt,name=callback_time,json=callbackTime,proto3" json:"callback_time,omitempty"`
	CardAccount           *CallbackCardPayBankCardAccount       `protobuf:"bytes,4,opt,name=card_account,json=cardAccount,proto3" json:"card_account,omitempty"`
	CryptocurrencyAccount *CallbackCardPayCryptoCurrencyAccount `protobuf:"bytes,5,opt,name=cryptocurrency_account,json=cryptocurrencyAccount,proto3" json:"cryptocurrency_account,omitempty"`
	Customer              *CardPayCustomer                      `protobuf:"bytes,6,opt,name=customer,proto3" json:"customer,omitempty"`
	EwalletAccount        *CardPayEWalletAccount                `protobuf:"bytes,7,opt,name=ewallet_account,json=ewalletAccount,proto3" json:"ewallet_account,omitempty"`
	// @inject_tag: json:"payment_data,omitempty"
	PaymentData *CallbackCardPayPaymentData `protobuf:"bytes,8,opt,name=payment_data,json=paymentData,proto3" json:"payment_data,omitempty"`
	// @inject_tag: json:"recurring_data,omitempty"
	RecurringData        *CardPayCallbackRecurringData `protobuf:"bytes,9,opt,name=recurring_data,json=recurringData,proto3" json:"recurring_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CardPayPaymentCallback) Reset()         { *m = CardPayPaymentCallback{} }
func (m *CardPayPaymentCallback) String() string { return proto.CompactTextString(m) }
func (*CardPayPaymentCallback) ProtoMessage()    {}
func (*CardPayPaymentCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{10}
}

func (m *CardPayPaymentCallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayPaymentCallback.Unmarshal(m, b)
}
func (m *CardPayPaymentCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayPaymentCallback.Marshal(b, m, deterministic)
}
func (m *CardPayPaymentCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayPaymentCallback.Merge(m, src)
}
func (m *CardPayPaymentCallback) XXX_Size() int {
	return xxx_messageInfo_CardPayPaymentCallback.Size(m)
}
func (m *CardPayPaymentCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayPaymentCallback.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayPaymentCallback proto.InternalMessageInfo

func (m *CardPayPaymentCallback) GetMerchantOrder() *CardPayMerchantOrder {
	if m != nil {
		return m.MerchantOrder
	}
	return nil
}

func (m *CardPayPaymentCallback) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *CardPayPaymentCallback) GetCallbackTime() string {
	if m != nil {
		return m.CallbackTime
	}
	return ""
}

func (m *CardPayPaymentCallback) GetCardAccount() *CallbackCardPayBankCardAccount {
	if m != nil {
		return m.CardAccount
	}
	return nil
}

func (m *CardPayPaymentCallback) GetCryptocurrencyAccount() *CallbackCardPayCryptoCurrencyAccount {
	if m != nil {
		return m.CryptocurrencyAccount
	}
	return nil
}

func (m *CardPayPaymentCallback) GetCustomer() *CardPayCustomer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *CardPayPaymentCallback) GetEwalletAccount() *CardPayEWalletAccount {
	if m != nil {
		return m.EwalletAccount
	}
	return nil
}

func (m *CardPayPaymentCallback) GetPaymentData() *CallbackCardPayPaymentData {
	if m != nil {
		return m.PaymentData
	}
	return nil
}

func (m *CardPayPaymentCallback) GetRecurringData() *CardPayCallbackRecurringData {
	if m != nil {
		return m.RecurringData
	}
	return nil
}

type CardPayRefundCallbackRefundData struct {
	// @inject_tag: validate:"required,numeric,gt=0"
	Amount float64 `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// @inject_tag: validate:"required"
	Created string `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	// @inject_tag: validate:"required,alpha,len=3"
	Currency string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	// @inject_tag: validate:"required"
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: validate:"required"
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AuthCode             string   `protobuf:"bytes,6,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	DeclineCode          string   `protobuf:"bytes,7,opt,name=decline_code,json=declineCode,proto3" json:"decline_code,omitempty"`
	DeclineReason        string   `protobuf:"bytes,8,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"`
	Is_3D                bool     `protobuf:"varint,9,opt,name=is_3d,json=is3d,proto3" json:"is_3d,omitempty"`
	Rrn                  string   `protobuf:"bytes,10,opt,name=rrn,proto3" json:"rrn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardPayRefundCallbackRefundData) Reset()         { *m = CardPayRefundCallbackRefundData{} }
func (m *CardPayRefundCallbackRefundData) String() string { return proto.CompactTextString(m) }
func (*CardPayRefundCallbackRefundData) ProtoMessage()    {}
func (*CardPayRefundCallbackRefundData) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{11}
}

func (m *CardPayRefundCallbackRefundData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayRefundCallbackRefundData.Unmarshal(m, b)
}
func (m *CardPayRefundCallbackRefundData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayRefundCallbackRefundData.Marshal(b, m, deterministic)
}
func (m *CardPayRefundCallbackRefundData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayRefundCallbackRefundData.Merge(m, src)
}
func (m *CardPayRefundCallbackRefundData) XXX_Size() int {
	return xxx_messageInfo_CardPayRefundCallbackRefundData.Size(m)
}
func (m *CardPayRefundCallbackRefundData) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayRefundCallbackRefundData.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayRefundCallbackRefundData proto.InternalMessageInfo

func (m *CardPayRefundCallbackRefundData) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CardPayRefundCallbackRefundData) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *CardPayRefundCallbackRefundData) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *CardPayRefundCallbackRefundData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CardPayRefundCallbackRefundData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CardPayRefundCallbackRefundData) GetAuthCode() string {
	if m != nil {
		return m.AuthCode
	}
	return ""
}

func (m *CardPayRefundCallbackRefundData) GetDeclineCode() string {
	if m != nil {
		return m.DeclineCode
	}
	return ""
}

func (m *CardPayRefundCallbackRefundData) GetDeclineReason() string {
	if m != nil {
		return m.DeclineReason
	}
	return ""
}

func (m *CardPayRefundCallbackRefundData) GetIs_3D() bool {
	if m != nil {
		return m.Is_3D
	}
	return false
}

func (m *CardPayRefundCallbackRefundData) GetRrn() string {
	if m != nil {
		return m.Rrn
	}
	return ""
}

type CardPayRefundCallbackPaymentData struct {
	// @inject_tag: validate:"required"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: validate:"numeric,gte=0"
	RemainingAmount      float64  `protobuf:"fixed64,2,opt,name=remaining_amount,json=remainingAmount,proto3" json:"remaining_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardPayRefundCallbackPaymentData) Reset()         { *m = CardPayRefundCallbackPaymentData{} }
func (m *CardPayRefundCallbackPaymentData) String() string { return proto.CompactTextString(m) }
func (*CardPayRefundCallbackPaymentData) ProtoMessage()    {}
func (*CardPayRefundCallbackPaymentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{12}
}

func (m *CardPayRefundCallbackPaymentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayRefundCallbackPaymentData.Unmarshal(m, b)
}
func (m *CardPayRefundCallbackPaymentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayRefundCallbackPaymentData.Marshal(b, m, deterministic)
}
func (m *CardPayRefundCallbackPaymentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayRefundCallbackPaymentData.Merge(m, src)
}
func (m *CardPayRefundCallbackPaymentData) XXX_Size() int {
	return xxx_messageInfo_CardPayRefundCallbackPaymentData.Size(m)
}
func (m *CardPayRefundCallbackPaymentData) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayRefundCallbackPaymentData.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayRefundCallbackPaymentData proto.InternalMessageInfo

func (m *CardPayRefundCallbackPaymentData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CardPayRefundCallbackPaymentData) GetRemainingAmount() float64 {
	if m != nil {
		return m.RemainingAmount
	}
	return 0
}

type CardPayRefundCallback struct {
	// @inject_tag: validate:"required"
	MerchantOrder *CardPayMerchantOrder `protobuf:"bytes,1,opt,name=merchant_order,json=merchantOrder,proto3" json:"merchant_order,omitempty"`
	// @inject_tag: validate:"required"
	PaymentMethod string `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	// @inject_tag: validate:"required"
	PaymentData *CardPayRefundCallbackPaymentData `protobuf:"bytes,3,opt,name=payment_data,json=paymentData,proto3" json:"payment_data,omitempty"`
	// @inject_tag: validate:"required"
	RefundData   *CardPayRefundCallbackRefundData `protobuf:"bytes,4,opt,name=refund_data,json=refundData,proto3" json:"refund_data,omitempty"`
	CallbackTime string                           `protobuf:"bytes,5,opt,name=callback_time,json=callbackTime,proto3" json:"callback_time,omitempty"`
	// @inject_tag: json:"-"
	CardAccount *CallbackCardPayBankCardAccount `protobuf:"bytes,6,opt,name=card_account,json=cardAccount,proto3" json:"card_account,omitempty"`
	Customer    *CardPayCustomer                `protobuf:"bytes,7,opt,name=customer,proto3" json:"customer,omitempty"`
	// @inject_tag: json:"-"
	EwalletAccount       *CardPayEWalletAccount `protobuf:"bytes,8,opt,name=ewallet_account,json=ewalletAccount,proto3" json:"ewallet_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CardPayRefundCallback) Reset()         { *m = CardPayRefundCallback{} }
func (m *CardPayRefundCallback) String() string { return proto.CompactTextString(m) }
func (*CardPayRefundCallback) ProtoMessage()    {}
func (*CardPayRefundCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_25bf4307d2315c21, []int{13}
}

func (m *CardPayRefundCallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayRefundCallback.Unmarshal(m, b)
}
func (m *CardPayRefundCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayRefundCallback.Marshal(b, m, deterministic)
}
func (m *CardPayRefundCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayRefundCallback.Merge(m, src)
}
func (m *CardPayRefundCallback) XXX_Size() int {
	return xxx_messageInfo_CardPayRefundCallback.Size(m)
}
func (m *CardPayRefundCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayRefundCallback.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayRefundCallback proto.InternalMessageInfo

func (m *CardPayRefundCallback) GetMerchantOrder() *CardPayMerchantOrder {
	if m != nil {
		return m.MerchantOrder
	}
	return nil
}

func (m *CardPayRefundCallback) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *CardPayRefundCallback) GetPaymentData() *CardPayRefundCallbackPaymentData {
	if m != nil {
		return m.PaymentData
	}
	return nil
}

func (m *CardPayRefundCallback) GetRefundData() *CardPayRefundCallbackRefundData {
	if m != nil {
		return m.RefundData
	}
	return nil
}

func (m *CardPayRefundCallback) GetCallbackTime() string {
	if m != nil {
		return m.CallbackTime
	}
	return ""
}

func (m *CardPayRefundCallback) GetCardAccount() *CallbackCardPayBankCardAccount {
	if m != nil {
		return m.CardAccount
	}
	return nil
}

func (m *CardPayRefundCallback) GetCustomer() *CardPayCustomer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *CardPayRefundCallback) GetEwalletAccount() *CardPayEWalletAccount {
	if m != nil {
		return m.EwalletAccount
	}
	return nil
}

func init() {
	proto.RegisterType((*CardPayAddress)(nil), "billing.CardPayAddress")
	proto.RegisterType((*CardPayItem)(nil), "billing.CardPayItem")
	proto.RegisterType((*CardPayMerchantOrder)(nil), "billing.CardPayMerchantOrder")
	proto.RegisterType((*CallbackCardPayBankCardAccount)(nil), "billing.CallbackCardPayBankCardAccount")
	proto.RegisterType((*CallbackCardPayCryptoCurrencyAccount)(nil), "billing.CallbackCardPayCryptoCurrencyAccount")
	proto.RegisterType((*CardPayCustomer)(nil), "billing.CardPayCustomer")
	proto.RegisterType((*CardPayEWalletAccount)(nil), "billing.CardPayEWalletAccount")
	proto.RegisterType((*CallbackCardPayPaymentData)(nil), "billing.CallbackCardPayPaymentData")
	proto.RegisterType((*CardPayCallbackRecurringDataFilling)(nil), "billing.CardPayCallbackRecurringDataFilling")
	proto.RegisterType((*CardPayCallbackRecurringData)(nil), "billing.CardPayCallbackRecurringData")
	proto.RegisterType((*CardPayPaymentCallback)(nil), "billing.CardPayPaymentCallback")
	proto.RegisterType((*CardPayRefundCallbackRefundData)(nil), "billing.CardPayRefundCallbackRefundData")
	proto.RegisterType((*CardPayRefundCallbackPaymentData)(nil), "billing.CardPayRefundCallbackPaymentData")
	proto.RegisterType((*CardPayRefundCallback)(nil), "billing.CardPayRefundCallback")
}

func init() { proto.RegisterFile("cardpay.proto", fileDescriptor_25bf4307d2315c21) }

var fileDescriptor_25bf4307d2315c21 = []byte{
	// 1086 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xdd, 0x6e, 0x1c, 0x35,
	0x14, 0xd6, 0xfe, 0xef, 0x9e, 0xc9, 0x6e, 0x22, 0x37, 0x59, 0x46, 0x85, 0x96, 0x30, 0x21, 0x6a,
	0x8a, 0x20, 0x42, 0x1b, 0x78, 0x80, 0x64, 0x43, 0x51, 0x50, 0x2b, 0xa2, 0x51, 0x25, 0x24, 0x24,
	0x34, 0x72, 0xc6, 0x6e, 0xd6, 0xca, 0xfc, 0xc9, 0xe3, 0x15, 0x5a, 0xde, 0x81, 0x3b, 0xae, 0xe1,
	0x8a, 0x77, 0xe0, 0x9e, 0x77, 0xe0, 0x3d, 0x78, 0x03, 0x64, 0xfb, 0x78, 0x32, 0x3b, 0xf9, 0x51,
	0xd4, 0x4a, 0x5c, 0xf5, 0x6e, 0xce, 0x67, 0xfb, 0x9c, 0xcf, 0xe7, 0xe7, 0xf3, 0x2e, 0x8c, 0x63,
	0x2a, 0x59, 0x41, 0x57, 0x87, 0x85, 0xcc, 0x55, 0x4e, 0x06, 0x17, 0x22, 0x49, 0x44, 0x76, 0x19,
	0xfc, 0xd6, 0x82, 0xc9, 0x9c, 0x4a, 0x76, 0x4e, 0x57, 0xc7, 0x8c, 0x49, 0x5e, 0x96, 0xc4, 0x87,
	0x41, 0x9c, 0x2f, 0x33, 0x25, 0x57, 0x7e, 0x6b, 0xb7, 0x75, 0x30, 0x0a, 0x9d, 0x49, 0x08, 0x74,
	0x63, 0xa1, 0x56, 0x7e, 0xdb, 0xc0, 0xe6, 0x9b, 0x6c, 0x43, 0xaf, 0x58, 0xe4, 0x19, 0xf7, 0x3b,
	0x06, 0xb4, 0x86, 0x46, 0x4b, 0x45, 0x15, 0xf7, 0xbb, 0x16, 0x35, 0x06, 0x99, 0x42, 0xbf, 0x54,
	0x92, 0x73, 0xe5, 0xf7, 0x0c, 0x8c, 0x16, 0xd9, 0x82, 0xce, 0x2f, 0xa2, 0xf0, 0xfb, 0x06, 0xd4,
	0x9f, 0x41, 0x0e, 0x1e, 0xb2, 0x3a, 0x53, 0x3c, 0xd5, 0x81, 0x33, 0x9a, 0x72, 0xe4, 0x63, 0xbe,
	0xc9, 0x2e, 0x78, 0x8c, 0x97, 0xb1, 0x14, 0x85, 0x12, 0x79, 0x86, 0x9c, 0xea, 0x90, 0x26, 0x61,
	0x98, 0x1b, 0x6a, 0xbd, 0xd0, 0x1a, 0x86, 0xb0, 0x14, 0xb1, 0xa5, 0xd6, 0x0a, 0xad, 0x11, 0xfc,
	0xd5, 0x82, 0x6d, 0x8c, 0xf8, 0x8a, 0xcb, 0x78, 0x41, 0x33, 0xf5, 0xbd, 0x64, 0x5c, 0x92, 0x09,
	0xb4, 0x05, 0xc3, 0xc0, 0x6d, 0xc1, 0x1e, 0x10, 0xf6, 0x33, 0xe8, 0x09, 0xc5, 0xd3, 0xd2, 0xef,
	0xec, 0x76, 0x0e, 0xbc, 0xd9, 0xf6, 0x21, 0xe6, 0xfa, 0xb0, 0x76, 0xa3, 0xd0, 0x6e, 0x21, 0x27,
	0xb0, 0x55, 0x2e, 0x44, 0x51, 0x88, 0xec, 0x32, 0xa2, 0x36, 0xff, 0x86, 0x97, 0x37, 0xfb, 0xa0,
	0x79, 0x0c, 0xcb, 0x13, 0x6e, 0xba, 0x03, 0x08, 0x04, 0x7f, 0xb4, 0xe0, 0xe9, 0x9c, 0x26, 0xc9,
	0x05, 0x8d, 0xaf, 0x70, 0xef, 0x09, 0xcd, 0xcc, 0xe7, 0x71, 0x6c, 0xef, 0x3c, 0x85, 0xfe, 0x22,
	0x4f, 0x18, 0x97, 0x78, 0x11, 0xb4, 0xc8, 0x97, 0xb0, 0x2d, 0xca, 0x72, 0xa9, 0xa3, 0x63, 0x8d,
	0xa3, 0x38, 0x67, 0x1c, 0x6f, 0x45, 0x70, 0x6d, 0x6e, 0x97, 0xe6, 0x39, 0xe3, 0xe4, 0x09, 0x40,
	0x4a, 0xcb, 0x2b, 0xce, 0xa2, 0x82, 0x66, 0x58, 0xf3, 0x91, 0x45, 0xce, 0xa9, 0x49, 0xb9, 0xca,
	0xaf, 0x78, 0xe6, 0xea, 0x6e, 0x8c, 0xe0, 0xef, 0x16, 0x7c, 0xda, 0x60, 0x38, 0x97, 0xab, 0x42,
	0xe5, 0xf3, 0xa5, 0x94, 0x3c, 0x8b, 0x57, 0x8e, 0xe7, 0x3e, 0x4c, 0x62, 0xb3, 0x50, 0x25, 0xc3,
	0xf2, 0x1d, 0x5b, 0xd4, 0x75, 0xe8, 0x0c, 0x76, 0x70, 0x9b, 0x92, 0x34, 0x2b, 0x69, 0xac, 0xf3,
	0x1e, 0x09, 0x86, 0xbc, 0x1f, 0xd9, 0xc5, 0xd7, 0xd7, 0x6b, 0x67, 0x4c, 0x13, 0x2f, 0x64, 0x1c,
	0xd1, 0xb4, 0xea, 0x88, 0x51, 0x38, 0x2a, 0x64, 0x7c, 0x6c, 0x00, 0xf2, 0x09, 0x6c, 0xe8, 0xe5,
	0x18, 0x09, 0x21, 0x7f, 0xaf, 0x90, 0xb1, 0xe3, 0x18, 0x44, 0xb0, 0xe9, 0xc8, 0x2f, 0x4b, 0x95,
	0xa7, 0x5c, 0xea, 0xeb, 0xf2, 0x94, 0x8a, 0x04, 0x69, 0x5a, 0xc3, 0xb4, 0x4c, 0x81, 0x5c, 0xda,
	0xa2, 0xc0, 0x16, 0xea, 0x54, 0x2d, 0x34, 0x85, 0x7e, 0x92, 0xc7, 0x34, 0x71, 0xd3, 0x81, 0x56,
	0xf0, 0x0c, 0x76, 0x30, 0xc0, 0x37, 0x3f, 0xd0, 0x24, 0xe1, 0xca, 0xa5, 0xa5, 0xd1, 0x83, 0xc1,
	0x3f, 0x6d, 0x78, 0xdc, 0xc8, 0xe7, 0x39, 0x5d, 0xa5, 0x3c, 0x53, 0xa7, 0x54, 0xd1, 0x1b, 0x2d,
	0x3b, 0x85, 0x3e, 0x5e, 0xbb, 0x6d, 0x5a, 0x1e, 0x2d, 0xf2, 0x21, 0x8c, 0xe8, 0x52, 0x2d, 0x6c,
	0xc9, 0x2d, 0xbd, 0xa1, 0x06, 0x4c, 0xa1, 0xb5, 0x0a, 0x48, 0x4e, 0x15, 0x67, 0xc8, 0xd2, 0x99,
	0xe4, 0x31, 0x0c, 0xab, 0x34, 0xd9, 0x39, 0xae, 0x6c, 0x9d, 0x46, 0xc6, 0xe3, 0x44, 0x64, 0xdc,
	0x7a, 0xed, 0xbb, 0xf1, 0x30, 0x98, 0x71, 0xbc, 0x0f, 0x13, 0xb7, 0x45, 0x72, 0x5a, 0xe6, 0x99,
	0x3f, 0xb0, 0x35, 0x46, 0x34, 0x34, 0x60, 0x73, 0xce, 0x86, 0x37, 0xe7, 0xec, 0x11, 0xf4, 0x44,
	0x19, 0x1d, 0x31, 0x7f, 0xb4, 0xdb, 0x3a, 0x18, 0x86, 0x5d, 0x51, 0x1e, 0x31, 0xa3, 0x14, 0xb9,
	0xe2, 0x3e, 0xa0, 0x52, 0xe4, 0x8a, 0x6b, 0x79, 0x91, 0x32, 0xf3, 0x3d, 0x2b, 0x2f, 0x52, 0x66,
	0x56, 0x88, 0xa8, 0x5a, 0x96, 0xfe, 0x86, 0x13, 0x22, 0x6d, 0x05, 0x5f, 0xc3, 0x9e, 0x2b, 0x31,
	0xa6, 0x37, 0xe4, 0xfa, 0x6e, 0x22, 0xbb, 0xd4, 0x99, 0x7d, 0x61, 0x27, 0xf2, 0x46, 0x3d, 0x7e,
	0xef, 0xc0, 0x47, 0xf7, 0x9d, 0x7b, 0x5f, 0x91, 0xb7, 0xad, 0x08, 0x39, 0x85, 0xfe, 0x1b, 0xa1,
	0x93, 0xee, 0x8f, 0x8d, 0x2c, 0x7e, 0xde, 0x94, 0xc5, 0xfb, 0x0a, 0x15, 0xe2, 0xd9, 0xe0, 0xdf,
	0x2e, 0x4c, 0xd7, 0x07, 0xc5, 0x1d, 0x23, 0xa7, 0x30, 0x49, 0x51, 0xf0, 0xa3, 0x5c, 0x3a, 0x89,
	0xf4, 0x66, 0x4f, 0x9a, 0x81, 0xd6, 0x9e, 0x85, 0x70, 0x9c, 0xae, 0xbd, 0x12, 0xfb, 0x30, 0x29,
	0xac, 0xe3, 0x28, 0xe5, 0x6a, 0x91, 0x3b, 0x29, 0x1a, 0x23, 0xfa, 0xca, 0x80, 0x64, 0x4f, 0xbf,
	0xc3, 0x36, 0x70, 0xa4, 0x44, 0xea, 0x6a, 0xbc, 0xe1, 0xc0, 0xd7, 0x22, 0xe5, 0xe4, 0x3b, 0xd8,
	0xd0, 0x8f, 0x75, 0x44, 0xed, 0xf4, 0xe3, 0x7b, 0xf0, 0xac, 0xc6, 0xe7, 0x3e, 0xad, 0x0f, 0xbd,
	0xb8, 0x26, 0xfc, 0x0c, 0xa6, 0x56, 0x0c, 0x5d, 0x3f, 0x54, 0x5e, 0x7b, 0xc6, 0xeb, 0x17, 0x77,
	0x79, 0xbd, 0x55, 0x9f, 0xc3, 0x9d, 0x75, 0x67, 0x2e, 0xca, 0x57, 0xba, 0xff, 0xac, 0x24, 0x9a,
	0xfe, 0xf2, 0x66, 0xfe, 0x8d, 0x32, 0xe1, 0x7a, 0x58, 0xed, 0x24, 0xdf, 0xc2, 0x26, 0xff, 0xd9,
	0xe8, 0x5c, 0x45, 0x6a, 0x60, 0x0e, 0x3f, 0x6d, 0x1e, 0x5e, 0x97, 0xc3, 0x70, 0x82, 0xc7, 0x5c,
	0xf8, 0x17, 0xb0, 0xe1, 0x92, 0xcf, 0xa8, 0xa2, 0xa6, 0x33, 0xbd, 0xd9, 0xde, 0x5d, 0x57, 0xab,
	0x49, 0x65, 0xe8, 0x15, 0x35, 0xdd, 0x7c, 0x09, 0x13, 0xe9, 0xba, 0xc8, 0x7a, 0x1a, 0x19, 0x4f,
	0xfb, 0x0f, 0xea, 0xb9, 0x70, 0x2c, 0xeb, 0x66, 0xf0, 0x67, 0x1b, 0x3e, 0xc6, 0xfd, 0x21, 0x7f,
	0xb3, 0xcc, 0xd8, 0xf5, 0x29, 0x6d, 0x99, 0x88, 0xd7, 0x3a, 0xd0, 0x5a, 0xd3, 0x81, 0xda, 0xa8,
	0xb7, 0xef, 0x1e, 0xf5, 0x4e, 0x63, 0xd4, 0xad, 0xca, 0x74, 0xeb, 0x2a, 0x83, 0x33, 0xd5, 0x5b,
	0x9b, 0xa9, 0x35, 0x95, 0xe9, 0x37, 0x54, 0xa6, 0xa9, 0x17, 0x83, 0x87, 0xe8, 0xc5, 0xf0, 0x36,
	0xbd, 0xb8, 0x55, 0x0d, 0x70, 0xf2, 0xa1, 0x9a, 0xfc, 0xe0, 0x27, 0xd8, 0xbd, 0x35, 0x4d, 0xf7,
	0xbd, 0x68, 0xcf, 0x61, 0x4b, 0xea, 0xb7, 0x36, 0x33, 0xbf, 0x9b, 0xea, 0x4a, 0xba, 0x59, 0xe1,
	0xf6, 0x61, 0x0f, 0x7e, 0xed, 0x56, 0xaf, 0xea, 0xba, 0xff, 0xff, 0x77, 0xf2, 0x5f, 0x36, 0x7a,
	0xb4, 0x63, 0x42, 0x3d, 0x6f, 0x86, 0xba, 0x33, 0x05, 0xeb, 0x9d, 0x7a, 0x06, 0x9e, 0x34, 0x3b,
	0xad, 0x33, 0xab, 0x10, 0x07, 0xf7, 0x3b, 0xbb, 0x6e, 0xbb, 0x10, 0xe4, 0x75, 0x0b, 0xde, 0x90,
	0xa4, 0xde, 0x03, 0x24, 0xa9, 0xff, 0x0e, 0x92, 0x54, 0x17, 0x8b, 0xc1, 0xbb, 0x88, 0xc5, 0xf0,
	0x6d, 0xc4, 0xe2, 0xc4, 0xfb, 0x71, 0x84, 0x07, 0x8a, 0x8b, 0x8b, 0xbe, 0xf9, 0x37, 0x74, 0xf4,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xc5, 0xc7, 0x14, 0x1e, 0x0d, 0x00, 0x00,
}
