// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paylink.proto

package billingpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePaylinkRequest struct {
	//@inject_tag: json:"id" validate:"omitempty,hexadecimal,len=24"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: json:"expires_at" validate:"omitempty,numeric,gte=0"
	ExpiresAt int64 `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	//@inject_tag: json:"products" validate:"required,gte=1,dive,hexadecimal,len=24"
	Products []string `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	//@inject_tag: json:"merchant_id" validate:"required,hexadecimal,len=24"
	MerchantId string `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	//@inject_tag: json:"project_id" validate:"required,hexadecimal,len=24"
	ProjectId string `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// @inject_tag: json:"name" validate:"required"
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// @inject_tag: json:"no_expiry_date"
	NoExpiryDate bool `protobuf:"varint,7,opt,name=no_expiry_date,json=noExpiryDate,proto3" json:"no_expiry_date,omitempty"`
	// @inject_tag: json:"products_type" validate="required,oneof=product key"
	ProductsType         string   `protobuf:"bytes,8,opt,name=products_type,json=productsType,proto3" json:"products_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaylinkRequest) Reset()         { *m = CreatePaylinkRequest{} }
func (m *CreatePaylinkRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePaylinkRequest) ProtoMessage()    {}
func (*CreatePaylinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e42f0d9b8e247bea, []int{0}
}

func (m *CreatePaylinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaylinkRequest.Unmarshal(m, b)
}
func (m *CreatePaylinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaylinkRequest.Marshal(b, m, deterministic)
}
func (m *CreatePaylinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaylinkRequest.Merge(m, src)
}
func (m *CreatePaylinkRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePaylinkRequest.Size(m)
}
func (m *CreatePaylinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaylinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaylinkRequest proto.InternalMessageInfo

func (m *CreatePaylinkRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreatePaylinkRequest) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *CreatePaylinkRequest) GetProducts() []string {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *CreatePaylinkRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *CreatePaylinkRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *CreatePaylinkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePaylinkRequest) GetNoExpiryDate() bool {
	if m != nil {
		return m.NoExpiryDate
	}
	return false
}

func (m *CreatePaylinkRequest) GetProductsType() string {
	if m != nil {
		return m.ProductsType
	}
	return ""
}

type Paylink struct {
	// @inject_tag: json:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: json:"object"
	Object string `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	// @inject_tag: json:"products"
	Products []string `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	// @inject_tag: json:"expires_at"
	ExpiresAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// @inject_tag: json:"created_at"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// @inject_tag: json:"updated_at"
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// @inject_tag: json:"merchant_id"
	MerchantId string `protobuf:"bytes,7,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// @inject_tag: json:"project_id"
	ProjectId string `protobuf:"bytes,8,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	// @inject_tag: json:"is_expired"
	IsExpired bool `protobuf:"varint,10,opt,name=is_expired,json=isExpired,proto3" json:"is_expired,omitempty"`
	// @inject_tag: json:"visits"
	Visits int32 `protobuf:"varint,11,opt,name=visits,proto3" json:"visits,omitempty"`
	// @inject_tag: json:"no_expiry_date"
	NoExpiryDate bool `protobuf:"varint,12,opt,name=no_expiry_date,json=noExpiryDate,proto3" json:"no_expiry_date,omitempty"`
	// @inject_tag: json:"products_type"
	ProductsType string `protobuf:"bytes,13,opt,name=products_type,json=productsType,proto3" json:"products_type,omitempty"`
	// @inject_tag: json:"-"
	Deleted bool `protobuf:"varint,14,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// @inject_tag: json:"total_transactions"
	TotalTransactions int32 `protobuf:"varint,15,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	// @inject_tag: json:"sales_count"
	SalesCount int32 `protobuf:"varint,16,opt,name=sales_count,json=salesCount,proto3" json:"sales_count,omitempty"`
	// @inject_tag: json:"returns_count"
	ReturnsCount int32 `protobuf:"varint,17,opt,name=returns_count,json=returnsCount,proto3" json:"returns_count,omitempty"`
	// @inject_tag: json:"conversion"
	Conversion float64 `protobuf:"fixed64,18,opt,name=conversion,proto3" json:"conversion,omitempty"`
	// @inject_tag: json:"gross_sales_amount"
	GrossSalesAmount float64 `protobuf:"fixed64,19,opt,name=gross_sales_amount,json=grossSalesAmount,proto3" json:"gross_sales_amount,omitempty"`
	// @inject_tag: json:"gross_returns_amount"
	GrossReturnsAmount float64 `protobuf:"fixed64,20,opt,name=gross_returns_amount,json=grossReturnsAmount,proto3" json:"gross_returns_amount,omitempty"`
	// @inject_tag: json:"gross_total_amount"
	GrossTotalAmount float64 `protobuf:"fixed64,21,opt,name=gross_total_amount,json=grossTotalAmount,proto3" json:"gross_total_amount,omitempty"`
	// @inject_tag: json:"transactions_currency"
	TransactionsCurrency string   `protobuf:"bytes,22,opt,name=transactions_currency,json=transactionsCurrency,proto3" json:"transactions_currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paylink) Reset()         { *m = Paylink{} }
func (m *Paylink) String() string { return proto.CompactTextString(m) }
func (*Paylink) ProtoMessage()    {}
func (*Paylink) Descriptor() ([]byte, []int) {
	return fileDescriptor_e42f0d9b8e247bea, []int{1}
}

func (m *Paylink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paylink.Unmarshal(m, b)
}
func (m *Paylink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paylink.Marshal(b, m, deterministic)
}
func (m *Paylink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paylink.Merge(m, src)
}
func (m *Paylink) XXX_Size() int {
	return xxx_messageInfo_Paylink.Size(m)
}
func (m *Paylink) XXX_DiscardUnknown() {
	xxx_messageInfo_Paylink.DiscardUnknown(m)
}

var xxx_messageInfo_Paylink proto.InternalMessageInfo

func (m *Paylink) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Paylink) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *Paylink) GetProducts() []string {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Paylink) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *Paylink) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Paylink) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Paylink) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *Paylink) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Paylink) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Paylink) GetIsExpired() bool {
	if m != nil {
		return m.IsExpired
	}
	return false
}

func (m *Paylink) GetVisits() int32 {
	if m != nil {
		return m.Visits
	}
	return 0
}

func (m *Paylink) GetNoExpiryDate() bool {
	if m != nil {
		return m.NoExpiryDate
	}
	return false
}

func (m *Paylink) GetProductsType() string {
	if m != nil {
		return m.ProductsType
	}
	return ""
}

func (m *Paylink) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Paylink) GetTotalTransactions() int32 {
	if m != nil {
		return m.TotalTransactions
	}
	return 0
}

func (m *Paylink) GetSalesCount() int32 {
	if m != nil {
		return m.SalesCount
	}
	return 0
}

func (m *Paylink) GetReturnsCount() int32 {
	if m != nil {
		return m.ReturnsCount
	}
	return 0
}

func (m *Paylink) GetConversion() float64 {
	if m != nil {
		return m.Conversion
	}
	return 0
}

func (m *Paylink) GetGrossSalesAmount() float64 {
	if m != nil {
		return m.GrossSalesAmount
	}
	return 0
}

func (m *Paylink) GetGrossReturnsAmount() float64 {
	if m != nil {
		return m.GrossReturnsAmount
	}
	return 0
}

func (m *Paylink) GetGrossTotalAmount() float64 {
	if m != nil {
		return m.GrossTotalAmount
	}
	return 0
}

func (m *Paylink) GetTransactionsCurrency() string {
	if m != nil {
		return m.TransactionsCurrency
	}
	return ""
}

type StatCommon struct {
	// @inject_tag: json:"-" bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: json:"paylink_id" bson:"-"
	PaylinkId string `protobuf:"bytes,2,opt,name=paylink_id,json=paylinkId,proto3" json:"paylink_id,omitempty"`
	// @inject_tag: json:"visits" bson:"-"
	Visits int32 `protobuf:"varint,3,opt,name=visits,proto3" json:"visits,omitempty"`
	// @inject_tag: json:"total_transactions" bson:"total_transactions"
	TotalTransactions int32 `protobuf:"varint,4,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	// @inject_tag: json:"sales_count" bson:"sales_count"
	SalesCount int32 `protobuf:"varint,5,opt,name=sales_count,json=salesCount,proto3" json:"sales_count,omitempty"`
	// @inject_tag: json:"returns_count" bson:"returns_count"
	ReturnsCount int32 `protobuf:"varint,6,opt,name=returns_count,json=returnsCount,proto3" json:"returns_count,omitempty"`
	// @inject_tag: json:"gross_sales_amount" bson:"gross_sales_amount"
	GrossSalesAmount float64 `protobuf:"fixed64,7,opt,name=gross_sales_amount,json=grossSalesAmount,proto3" json:"gross_sales_amount,omitempty"`
	// @inject_tag: json:"gross_returns_amount" bson:"gross_returns_amount"
	GrossReturnsAmount float64 `protobuf:"fixed64,8,opt,name=gross_returns_amount,json=grossReturnsAmount,proto3" json:"gross_returns_amount,omitempty"`
	// @inject_tag: json:"gross_total_amount" bson:"gross_total_amount"
	GrossTotalAmount float64 `protobuf:"fixed64,9,opt,name=gross_total_amount,json=grossTotalAmount,proto3" json:"gross_total_amount,omitempty"`
	// @inject_tag: json:"transactions_currency" bson:"transactions_currency"
	TransactionsCurrency string `protobuf:"bytes,10,opt,name=transactions_currency,json=transactionsCurrency,proto3" json:"transactions_currency,omitempty"`
	// @inject_tag: json:"conversion" bson:"-"
	Conversion float64 `protobuf:"fixed64,11,opt,name=conversion,proto3" json:"conversion,omitempty"`
	// @inject_tag: json:"country_code" bson:"-"
	CountryCode string `protobuf:"bytes,12,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// @inject_tag: json:"date" bson:"-"
	Date string `protobuf:"bytes,13,opt,name=date,proto3" json:"date,omitempty"`
	// @inject_tag: json:"referrer_host" bson:"-"
	ReferrerHost string `protobuf:"bytes,14,opt,name=referrer_host,json=referrerHost,proto3" json:"referrer_host,omitempty"`
	// @inject_tag: json:"utm" bson:"-"
	Utm                  *Utm     `protobuf:"bytes,15,opt,name=utm,proto3" json:"utm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatCommon) Reset()         { *m = StatCommon{} }
func (m *StatCommon) String() string { return proto.CompactTextString(m) }
func (*StatCommon) ProtoMessage()    {}
func (*StatCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_e42f0d9b8e247bea, []int{2}
}

func (m *StatCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatCommon.Unmarshal(m, b)
}
func (m *StatCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatCommon.Marshal(b, m, deterministic)
}
func (m *StatCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatCommon.Merge(m, src)
}
func (m *StatCommon) XXX_Size() int {
	return xxx_messageInfo_StatCommon.Size(m)
}
func (m *StatCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_StatCommon.DiscardUnknown(m)
}

var xxx_messageInfo_StatCommon proto.InternalMessageInfo

func (m *StatCommon) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StatCommon) GetPaylinkId() string {
	if m != nil {
		return m.PaylinkId
	}
	return ""
}

func (m *StatCommon) GetVisits() int32 {
	if m != nil {
		return m.Visits
	}
	return 0
}

func (m *StatCommon) GetTotalTransactions() int32 {
	if m != nil {
		return m.TotalTransactions
	}
	return 0
}

func (m *StatCommon) GetSalesCount() int32 {
	if m != nil {
		return m.SalesCount
	}
	return 0
}

func (m *StatCommon) GetReturnsCount() int32 {
	if m != nil {
		return m.ReturnsCount
	}
	return 0
}

func (m *StatCommon) GetGrossSalesAmount() float64 {
	if m != nil {
		return m.GrossSalesAmount
	}
	return 0
}

func (m *StatCommon) GetGrossReturnsAmount() float64 {
	if m != nil {
		return m.GrossReturnsAmount
	}
	return 0
}

func (m *StatCommon) GetGrossTotalAmount() float64 {
	if m != nil {
		return m.GrossTotalAmount
	}
	return 0
}

func (m *StatCommon) GetTransactionsCurrency() string {
	if m != nil {
		return m.TransactionsCurrency
	}
	return ""
}

func (m *StatCommon) GetConversion() float64 {
	if m != nil {
		return m.Conversion
	}
	return 0
}

func (m *StatCommon) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *StatCommon) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *StatCommon) GetReferrerHost() string {
	if m != nil {
		return m.ReferrerHost
	}
	return ""
}

func (m *StatCommon) GetUtm() *Utm {
	if m != nil {
		return m.Utm
	}
	return nil
}

type Utm struct {
	// @inject_tag: json:"utm_source"
	UtmSource string `protobuf:"bytes,1,opt,name=utm_source,json=utmSource,proto3" json:"utm_source,omitempty"`
	// @inject_tag: json:"utm_medium"
	UtmMedium string `protobuf:"bytes,2,opt,name=utm_medium,json=utmMedium,proto3" json:"utm_medium,omitempty"`
	// @inject_tag: json:"utm_campaign"
	UtmCampaign          string   `protobuf:"bytes,3,opt,name=utm_campaign,json=utmCampaign,proto3" json:"utm_campaign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Utm) Reset()         { *m = Utm{} }
func (m *Utm) String() string { return proto.CompactTextString(m) }
func (*Utm) ProtoMessage()    {}
func (*Utm) Descriptor() ([]byte, []int) {
	return fileDescriptor_e42f0d9b8e247bea, []int{3}
}

func (m *Utm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Utm.Unmarshal(m, b)
}
func (m *Utm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Utm.Marshal(b, m, deterministic)
}
func (m *Utm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Utm.Merge(m, src)
}
func (m *Utm) XXX_Size() int {
	return xxx_messageInfo_Utm.Size(m)
}
func (m *Utm) XXX_DiscardUnknown() {
	xxx_messageInfo_Utm.DiscardUnknown(m)
}

var xxx_messageInfo_Utm proto.InternalMessageInfo

func (m *Utm) GetUtmSource() string {
	if m != nil {
		return m.UtmSource
	}
	return ""
}

func (m *Utm) GetUtmMedium() string {
	if m != nil {
		return m.UtmMedium
	}
	return ""
}

func (m *Utm) GetUtmCampaign() string {
	if m != nil {
		return m.UtmCampaign
	}
	return ""
}

type GroupStatCommon struct {
	// @inject_tag: json:"top" bson:"top"
	Top []*StatCommon `protobuf:"bytes,1,rep,name=top,proto3" json:"top,omitempty"`
	// @inject_tag: json:"total" bson:"total"
	Total                *StatCommon `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GroupStatCommon) Reset()         { *m = GroupStatCommon{} }
func (m *GroupStatCommon) String() string { return proto.CompactTextString(m) }
func (*GroupStatCommon) ProtoMessage()    {}
func (*GroupStatCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_e42f0d9b8e247bea, []int{4}
}

func (m *GroupStatCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupStatCommon.Unmarshal(m, b)
}
func (m *GroupStatCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupStatCommon.Marshal(b, m, deterministic)
}
func (m *GroupStatCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupStatCommon.Merge(m, src)
}
func (m *GroupStatCommon) XXX_Size() int {
	return xxx_messageInfo_GroupStatCommon.Size(m)
}
func (m *GroupStatCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupStatCommon.DiscardUnknown(m)
}

var xxx_messageInfo_GroupStatCommon proto.InternalMessageInfo

func (m *GroupStatCommon) GetTop() []*StatCommon {
	if m != nil {
		return m.Top
	}
	return nil
}

func (m *GroupStatCommon) GetTotal() *StatCommon {
	if m != nil {
		return m.Total
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatePaylinkRequest)(nil), "paylink.CreatePaylinkRequest")
	proto.RegisterType((*Paylink)(nil), "paylink.Paylink")
	proto.RegisterType((*StatCommon)(nil), "paylink.StatCommon")
	proto.RegisterType((*Utm)(nil), "paylink.Utm")
	proto.RegisterType((*GroupStatCommon)(nil), "paylink.GroupStatCommon")
}

func init() { proto.RegisterFile("paylink.proto", fileDescriptor_e42f0d9b8e247bea) }

var fileDescriptor_e42f0d9b8e247bea = []byte{
	// 775 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4d, 0x6f, 0x1b, 0x37,
	0x10, 0x85, 0x24, 0xeb, 0x63, 0x67, 0x65, 0x27, 0x61, 0x9c, 0x80, 0x30, 0x90, 0x46, 0x55, 0x5b,
	0x40, 0x05, 0x5a, 0xa5, 0x70, 0x4e, 0x39, 0xba, 0x6a, 0xd0, 0xfa, 0x50, 0xa0, 0x58, 0x3b, 0x97,
	0x5e, 0x16, 0xd4, 0x2e, 0xad, 0xb0, 0x15, 0x97, 0x5b, 0x72, 0x36, 0xa8, 0x6e, 0xfd, 0x37, 0xfd,
	0x27, 0xfd, 0x5d, 0x05, 0x87, 0x5c, 0x77, 0x13, 0xcb, 0xb5, 0x7d, 0x13, 0xdf, 0x7b, 0x33, 0xe4,
	0xcc, 0x9b, 0x59, 0xc1, 0x61, 0x2d, 0x76, 0x5b, 0x55, 0xfd, 0xbe, 0xac, 0xad, 0x41, 0xc3, 0xc6,
	0xf1, 0x78, 0xf2, 0x72, 0x63, 0xcc, 0x66, 0x2b, 0x5f, 0x11, 0xbc, 0x6e, 0xae, 0x5e, 0xa1, 0xd2,
	0xd2, 0xa1, 0xd0, 0x75, 0x50, 0xce, 0xff, 0xea, 0xc3, 0xf1, 0xca, 0x4a, 0x81, 0xf2, 0x97, 0x10,
	0x92, 0xc9, 0x3f, 0x1a, 0xe9, 0x90, 0x1d, 0x41, 0x5f, 0x95, 0xbc, 0x37, 0xeb, 0x2d, 0x92, 0xac,
	0xaf, 0x4a, 0xf6, 0x02, 0x40, 0xfe, 0x59, 0x2b, 0x2b, 0x5d, 0x2e, 0x90, 0xf7, 0x67, 0xbd, 0xc5,
	0x20, 0x4b, 0x22, 0x72, 0x86, 0xec, 0x04, 0x26, 0xb5, 0x35, 0x65, 0x53, 0xa0, 0xe3, 0x83, 0xd9,
	0x60, 0x91, 0x64, 0xd7, 0x67, 0xf6, 0x12, 0x52, 0x2d, 0x6d, 0xf1, 0x5e, 0x54, 0x98, 0xab, 0x92,
	0x1f, 0x50, 0x4e, 0x68, 0xa1, 0x73, 0xca, 0x5d, 0x5b, 0xf3, 0x9b, 0x2c, 0x88, 0x1f, 0x12, 0x9f,
	0x44, 0xe4, 0xbc, 0x64, 0x0c, 0x0e, 0x2a, 0xa1, 0x25, 0x1f, 0x11, 0x41, 0xbf, 0xd9, 0x97, 0x70,
	0x54, 0x99, 0x9c, 0xee, 0xdf, 0xe5, 0xa5, 0x40, 0xc9, 0xc7, 0xb3, 0xde, 0x62, 0x92, 0x4d, 0x2b,
	0xf3, 0x96, 0xc0, 0x1f, 0x04, 0x4a, 0xf6, 0x05, 0x1c, 0xb6, 0xaf, 0xc8, 0x71, 0x57, 0x4b, 0x3e,
	0xa1, 0x14, 0xd3, 0x16, 0xbc, 0xdc, 0xd5, 0x72, 0xfe, 0xcf, 0x08, 0xc6, 0xb1, 0xf8, 0x1b, 0x55,
	0x3f, 0x87, 0x91, 0x59, 0xfb, 0x67, 0x50, 0xc5, 0x49, 0x16, 0x4f, 0xff, 0x5b, 0xee, 0x9b, 0x8f,
	0x3a, 0xe5, 0xab, 0x4d, 0x4f, 0x4f, 0x96, 0xc1, 0x88, 0x65, 0x6b, 0xc4, 0xf2, 0xb2, 0x35, 0xa2,
	0xdb, 0xc5, 0x37, 0x00, 0x05, 0x99, 0x51, 0xfa, 0xd0, 0xe1, 0xdd, 0xa1, 0x51, 0x1d, 0x42, 0x9b,
	0xba, 0x6c, 0x43, 0x47, 0x77, 0x87, 0x46, 0xf5, 0x19, 0x7e, 0xea, 0xcf, 0xf8, 0x0e, 0x7f, 0x26,
	0xb7, 0xf9, 0x93, 0x74, 0xfc, 0x79, 0x01, 0xa0, 0x5c, 0xf0, 0x47, 0x96, 0x1c, 0xc8, 0x9b, 0x44,
	0xb9, 0xb7, 0x01, 0xf0, 0x7d, 0xfd, 0xa0, 0x9c, 0x42, 0xc7, 0xd3, 0x59, 0x6f, 0x31, 0xcc, 0xe2,
	0x69, 0x8f, 0xad, 0xd3, 0xfb, 0xd8, 0x7a, 0x78, 0xd3, 0x56, 0xc6, 0x61, 0x5c, 0xca, 0xad, 0x44,
	0x59, 0xf2, 0x23, 0xca, 0xd1, 0x1e, 0xd9, 0xb7, 0xc0, 0xd0, 0xa0, 0xd8, 0xe6, 0x68, 0x45, 0xe5,
	0x44, 0x81, 0xca, 0x54, 0x8e, 0x3f, 0xa2, 0x87, 0x3c, 0x21, 0xe6, 0xb2, 0x43, 0xf8, 0xf6, 0x38,
	0xb1, 0x95, 0x2e, 0x2f, 0x4c, 0x53, 0x21, 0x7f, 0x4c, 0x3a, 0x20, 0x68, 0xe5, 0x11, 0xff, 0x1c,
	0x2b, 0xb1, 0xb1, 0x55, 0x2b, 0x79, 0x42, 0x92, 0x69, 0x04, 0x83, 0xe8, 0x33, 0x80, 0xc2, 0x54,
	0x1f, 0xa4, 0x75, 0xca, 0x54, 0x9c, 0xcd, 0x7a, 0x8b, 0x5e, 0xd6, 0x41, 0xd8, 0x37, 0xc0, 0x36,
	0xd6, 0x38, 0x97, 0x87, 0xbb, 0x84, 0xa6, 0x4c, 0x4f, 0x49, 0xf7, 0x98, 0x98, 0x0b, 0x4f, 0x9c,
	0x11, 0xce, 0xbe, 0x83, 0xe3, 0xa0, 0x6e, 0x2f, 0x8e, 0xfa, 0x63, 0xd2, 0x87, 0x4c, 0x59, 0xa0,
	0x62, 0xc4, 0x75, 0xfe, 0x50, 0x7a, 0xd4, 0x3f, 0xeb, 0xe4, 0xbf, 0xf4, 0x44, 0x54, 0xbf, 0x86,
	0x67, 0xdd, 0xe6, 0xe4, 0x45, 0x63, 0xad, 0xac, 0x8a, 0x1d, 0x7f, 0x4e, 0x9d, 0x3e, 0xee, 0x92,
	0xab, 0xc8, 0xcd, 0xff, 0x3e, 0x00, 0xb8, 0x40, 0x81, 0x2b, 0xa3, 0xb5, 0xa9, 0xf6, 0x7d, 0x41,
	0xe2, 0x67, 0xc9, 0x4f, 0x51, 0x3f, 0x4e, 0x51, 0x40, 0xce, 0xbb, 0x23, 0x31, 0xf8, 0x68, 0x24,
	0xf6, 0xbb, 0x75, 0x70, 0x4f, 0xb7, 0x86, 0x77, 0xbb, 0x35, 0xda, 0xe3, 0xd6, 0x7e, 0x37, 0xc6,
	0x0f, 0x74, 0x63, 0xf2, 0x40, 0x37, 0x92, 0x87, 0xba, 0x01, 0xb7, 0xbb, 0xf1, 0xc9, 0xc0, 0xa5,
	0x37, 0x06, 0xee, 0x73, 0x98, 0x52, 0xfd, 0x76, 0x97, 0x17, 0xa6, 0x0c, 0x8b, 0x96, 0x64, 0x69,
	0xc4, 0x56, 0xa6, 0x94, 0x7e, 0xb1, 0x69, 0x07, 0xc3, 0x7a, 0xd1, 0xef, 0xd0, 0xbe, 0x2b, 0x69,
	0xad, 0xb4, 0xf9, 0x7b, 0xe3, 0x90, 0x96, 0x2b, 0xf1, 0xed, 0x0b, 0xe0, 0x4f, 0xc6, 0xf9, 0x61,
	0x1f, 0x34, 0xa8, 0x69, 0xa5, 0xd2, 0xd3, 0xe9, 0xb2, 0xfd, 0x73, 0x7a, 0x87, 0x3a, 0xf3, 0xc4,
	0xfc, 0x0a, 0x06, 0xef, 0x50, 0xfb, 0x89, 0x68, 0x50, 0xe7, 0xce, 0x34, 0xb6, 0x90, 0x71, 0x52,
	0x92, 0x06, 0xf5, 0x05, 0x01, 0x2d, 0xad, 0x65, 0xa9, 0x1a, 0xdd, 0x0e, 0x4c, 0x83, 0xfa, 0x67,
	0x02, 0x7c, 0x01, 0x9e, 0x2e, 0x84, 0xae, 0x85, 0xda, 0x54, 0x34, 0x36, 0x49, 0x96, 0x36, 0xa8,
	0x57, 0x11, 0x9a, 0x17, 0xf0, 0xe8, 0x47, 0x6b, 0x9a, 0xba, 0x33, 0x95, 0x5f, 0xc1, 0x00, 0x4d,
	0xcd, 0x7b, 0xb3, 0xc1, 0x22, 0x3d, 0x7d, 0x7a, 0xfd, 0xb4, 0xff, 0x14, 0x99, 0xe7, 0xd9, 0xd7,
	0x30, 0x24, 0x6b, 0xe8, 0xda, 0x5b, 0x84, 0x41, 0xf1, 0x7d, 0xfa, 0x6b, 0xb2, 0x56, 0xdb, 0xad,
	0xaa, 0x36, 0xf5, 0x7a, 0x3d, 0xa2, 0x4f, 0xed, 0xeb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x38,
	0x61, 0x9c, 0xcf, 0x91, 0x07, 0x00, 0x00,
}
