// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: signer.proto

package document_signerpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
	server "github.com/unistack-org/micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DocumentSignerService service

func NewDocumentSignerServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for DocumentSignerService service

type DocumentSignerService interface {
	CreateSignature(ctx context.Context, req *CreateSignatureRequest, opts ...client.CallOption) (*CreateSignatureResponse, error)
	GetSignatureUrl(ctx context.Context, req *GetSignatureUrlRequest, opts ...client.CallOption) (*GetSignatureUrlResponse, error)
}

type documentSignerService struct {
	c    client.Client
	name string
}

func NewDocumentSignerService(name string, c client.Client) DocumentSignerService {
	return &documentSignerService{
		c:    c,
		name: name,
	}
}

func (c *documentSignerService) CreateSignature(ctx context.Context, req *CreateSignatureRequest, opts ...client.CallOption) (*CreateSignatureResponse, error) {
	rsp := &CreateSignatureResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "DocumentSignerService.CreateSignature", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *documentSignerService) GetSignatureUrl(ctx context.Context, req *GetSignatureUrlRequest, opts ...client.CallOption) (*GetSignatureUrlResponse, error) {
	rsp := &GetSignatureUrlResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "DocumentSignerService.GetSignatureUrl", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// Server API for DocumentSignerService service

type DocumentSignerServiceHandler interface {
	CreateSignature(context.Context, *CreateSignatureRequest, *CreateSignatureResponse) error
	GetSignatureUrl(context.Context, *GetSignatureUrlRequest, *GetSignatureUrlResponse) error
}

func RegisterDocumentSignerServiceHandler(s server.Server, hdlr DocumentSignerServiceHandler, opts ...server.HandlerOption) error {
	type documentSignerService interface {
		CreateSignature(ctx context.Context, req *CreateSignatureRequest, rsp *CreateSignatureResponse) error
		GetSignatureUrl(ctx context.Context, req *GetSignatureUrlRequest, rsp *GetSignatureUrlResponse) error
	}
	type DocumentSignerService struct {
		documentSignerService
	}
	h := &documentSignerServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DocumentSignerService{h}, opts...))
}

type documentSignerServiceHandler struct {
	DocumentSignerServiceHandler
}

func (h *documentSignerServiceHandler) CreateSignature(ctx context.Context, req *CreateSignatureRequest, rsp *CreateSignatureResponse) error {
	return h.DocumentSignerServiceHandler.CreateSignature(ctx, req, rsp)
}

func (h *documentSignerServiceHandler) GetSignatureUrl(ctx context.Context, req *GetSignatureUrlRequest, rsp *GetSignatureUrlResponse) error {
	return h.DocumentSignerServiceHandler.GetSignatureUrl(ctx, req, rsp)
}
